//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdministrativeUnitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdministrativeUnitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="administrativeUnitTypeCode" type="{urn:gs1:ecom:ecom_common:xsd:3}AdministrativeUnitTypeCodeType"/>
 *         &lt;element name="gln" type="{urn:gs1:shared:shared_common:xsd:3}GLNType" minOccurs="0"/>
 *         &lt;element name="internalAdministrativeUnitIdentification" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdministrativeUnitType", propOrder = {
    "administrativeUnitTypeCode",
    "gln",
    "internalAdministrativeUnitIdentification"
})
public class AdministrativeUnitType {

    @XmlElement(required = true)
    protected AdministrativeUnitTypeCodeType administrativeUnitTypeCode;
    protected String gln;
    protected String internalAdministrativeUnitIdentification;

    /**
     * Gets the value of the administrativeUnitTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link AdministrativeUnitTypeCodeType }
     *     
     */
    public AdministrativeUnitTypeCodeType getAdministrativeUnitTypeCode() {
        return administrativeUnitTypeCode;
    }

    /**
     * Sets the value of the administrativeUnitTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdministrativeUnitTypeCodeType }
     *     
     */
    public void setAdministrativeUnitTypeCode(AdministrativeUnitTypeCodeType value) {
        this.administrativeUnitTypeCode = value;
    }

    /**
     * Gets the value of the gln property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGln() {
        return gln;
    }

    /**
     * Sets the value of the gln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGln(String value) {
        this.gln = value;
    }

    /**
     * Gets the value of the internalAdministrativeUnitIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalAdministrativeUnitIdentification() {
        return internalAdministrativeUnitIdentification;
    }

    /**
     * Sets the value of the internalAdministrativeUnitIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalAdministrativeUnitIdentification(String value) {
        this.internalAdministrativeUnitIdentification = value;
    }

}
