//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArtworkContentGraphicElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArtworkContentGraphicElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="graphicElementTypeCode" type="{urn:gs1:ecom:artwork_content_common:xsd:3}GraphicElementTypeCodeType"/>
 *         &lt;element name="instanceSequence" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="localeSequence" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="isContentApproved" type="{urn:gs1:shared:shared_common:xsd:3}NonBinaryLogicEnumerationType"/>
 *         &lt;element name="forPlacementOnly" type="{urn:gs1:shared:shared_common:xsd:3}NonBinaryLogicEnumerationType"/>
 *         &lt;element name="graphicElementDescription" type="{urn:gs1:shared:shared_common:xsd:3}Description200Type" minOccurs="0"/>
 *         &lt;element name="optionSequence" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="prioritySequence" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="expectedNumberOfOccurrences" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="actualNumberOfOccurrences" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="note" type="{urn:gs1:shared:shared_common:xsd:3}Description500Type" minOccurs="0"/>
 *         &lt;element name="sourceReference" type="{urn:gs1:ecom:ecom_common:xsd:3}SourceReferenceType" minOccurs="0"/>
 *         &lt;element name="graphicElementReference" type="{urn:gs1:ecom:ecom_common:xsd:3}SourceReferenceType" minOccurs="0"/>
 *         &lt;element name="artworkContentResponseStatus" type="{urn:gs1:ecom:artwork_content_common:xsd:3}ArtworkContentResponseStatusType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArtworkContentGraphicElementType", namespace = "urn:gs1:ecom:artwork_content_common:xsd:3", propOrder = {
    "graphicElementTypeCode",
    "instanceSequence",
    "localeSequence",
    "isContentApproved",
    "forPlacementOnly",
    "graphicElementDescription",
    "optionSequence",
    "prioritySequence",
    "expectedNumberOfOccurrences",
    "actualNumberOfOccurrences",
    "note",
    "sourceReference",
    "graphicElementReference",
    "artworkContentResponseStatus"
})
public class ArtworkContentGraphicElementType {

    @XmlElement(required = true)
    protected GraphicElementTypeCodeType graphicElementTypeCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger instanceSequence;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger localeSequence;
    @XmlElement(required = true)
    protected NonBinaryLogicEnumerationType isContentApproved;
    @XmlElement(required = true)
    protected NonBinaryLogicEnumerationType forPlacementOnly;
    protected Description200Type graphicElementDescription;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger optionSequence;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger prioritySequence;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger expectedNumberOfOccurrences;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger actualNumberOfOccurrences;
    protected Description500Type note;
    protected SourceReferenceType sourceReference;
    protected SourceReferenceType graphicElementReference;
    protected ArtworkContentResponseStatusType artworkContentResponseStatus;

    /**
     * Gets the value of the graphicElementTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link GraphicElementTypeCodeType }
     *     
     */
    public GraphicElementTypeCodeType getGraphicElementTypeCode() {
        return graphicElementTypeCode;
    }

    /**
     * Sets the value of the graphicElementTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link GraphicElementTypeCodeType }
     *     
     */
    public void setGraphicElementTypeCode(GraphicElementTypeCodeType value) {
        this.graphicElementTypeCode = value;
    }

    /**
     * Gets the value of the instanceSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstanceSequence() {
        return instanceSequence;
    }

    /**
     * Sets the value of the instanceSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstanceSequence(BigInteger value) {
        this.instanceSequence = value;
    }

    /**
     * Gets the value of the localeSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocaleSequence() {
        return localeSequence;
    }

    /**
     * Sets the value of the localeSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocaleSequence(BigInteger value) {
        this.localeSequence = value;
    }

    /**
     * Gets the value of the isContentApproved property.
     * 
     * @return
     *     possible object is
     *     {@link NonBinaryLogicEnumerationType }
     *     
     */
    public NonBinaryLogicEnumerationType getIsContentApproved() {
        return isContentApproved;
    }

    /**
     * Sets the value of the isContentApproved property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonBinaryLogicEnumerationType }
     *     
     */
    public void setIsContentApproved(NonBinaryLogicEnumerationType value) {
        this.isContentApproved = value;
    }

    /**
     * Gets the value of the forPlacementOnly property.
     * 
     * @return
     *     possible object is
     *     {@link NonBinaryLogicEnumerationType }
     *     
     */
    public NonBinaryLogicEnumerationType getForPlacementOnly() {
        return forPlacementOnly;
    }

    /**
     * Sets the value of the forPlacementOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonBinaryLogicEnumerationType }
     *     
     */
    public void setForPlacementOnly(NonBinaryLogicEnumerationType value) {
        this.forPlacementOnly = value;
    }

    /**
     * Gets the value of the graphicElementDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Description200Type }
     *     
     */
    public Description200Type getGraphicElementDescription() {
        return graphicElementDescription;
    }

    /**
     * Sets the value of the graphicElementDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description200Type }
     *     
     */
    public void setGraphicElementDescription(Description200Type value) {
        this.graphicElementDescription = value;
    }

    /**
     * Gets the value of the optionSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOptionSequence() {
        return optionSequence;
    }

    /**
     * Sets the value of the optionSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOptionSequence(BigInteger value) {
        this.optionSequence = value;
    }

    /**
     * Gets the value of the prioritySequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrioritySequence() {
        return prioritySequence;
    }

    /**
     * Sets the value of the prioritySequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrioritySequence(BigInteger value) {
        this.prioritySequence = value;
    }

    /**
     * Gets the value of the expectedNumberOfOccurrences property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExpectedNumberOfOccurrences() {
        return expectedNumberOfOccurrences;
    }

    /**
     * Sets the value of the expectedNumberOfOccurrences property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExpectedNumberOfOccurrences(BigInteger value) {
        this.expectedNumberOfOccurrences = value;
    }

    /**
     * Gets the value of the actualNumberOfOccurrences property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getActualNumberOfOccurrences() {
        return actualNumberOfOccurrences;
    }

    /**
     * Sets the value of the actualNumberOfOccurrences property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setActualNumberOfOccurrences(BigInteger value) {
        this.actualNumberOfOccurrences = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link Description500Type }
     *     
     */
    public Description500Type getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description500Type }
     *     
     */
    public void setNote(Description500Type value) {
        this.note = value;
    }

    /**
     * Gets the value of the sourceReference property.
     * 
     * @return
     *     possible object is
     *     {@link SourceReferenceType }
     *     
     */
    public SourceReferenceType getSourceReference() {
        return sourceReference;
    }

    /**
     * Sets the value of the sourceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceReferenceType }
     *     
     */
    public void setSourceReference(SourceReferenceType value) {
        this.sourceReference = value;
    }

    /**
     * Gets the value of the graphicElementReference property.
     * 
     * @return
     *     possible object is
     *     {@link SourceReferenceType }
     *     
     */
    public SourceReferenceType getGraphicElementReference() {
        return graphicElementReference;
    }

    /**
     * Sets the value of the graphicElementReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceReferenceType }
     *     
     */
    public void setGraphicElementReference(SourceReferenceType value) {
        this.graphicElementReference = value;
    }

    /**
     * Gets the value of the artworkContentResponseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ArtworkContentResponseStatusType }
     *     
     */
    public ArtworkContentResponseStatusType getArtworkContentResponseStatus() {
        return artworkContentResponseStatus;
    }

    /**
     * Sets the value of the artworkContentResponseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArtworkContentResponseStatusType }
     *     
     */
    public void setArtworkContentResponseStatus(ArtworkContentResponseStatusType value) {
        this.artworkContentResponseStatus = value;
    }

}
