//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DeliverDateInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliverDateInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deliverDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="deliverDateType" type="{urn:gs1:ecom:ecom_common:xsd:3}DeliverDateTypeCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliverDateInformationType", propOrder = {
    "deliverDate",
    "deliverDateType"
})
public class DeliverDateInformationType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliverDate;
    @XmlElement(required = true)
    protected DeliverDateTypeCodeType deliverDateType;

    /**
     * Gets the value of the deliverDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeliverDate() {
        return deliverDate;
    }

    /**
     * Sets the value of the deliverDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeliverDate(XMLGregorianCalendar value) {
        this.deliverDate = value;
    }

    /**
     * Gets the value of the deliverDateType property.
     * 
     * @return
     *     possible object is
     *     {@link DeliverDateTypeCodeType }
     *     
     */
    public DeliverDateTypeCodeType getDeliverDateType() {
        return deliverDateType;
    }

    /**
     * Sets the value of the deliverDateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliverDateTypeCodeType }
     *     
     */
    public void setDeliverDateType(DeliverDateTypeCodeType value) {
        this.deliverDateType = value;
    }

}
