//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DespatchInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DespatchInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actualShipDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="despatchDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="estimatedDeliveryDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="estimatedDeliveryDateTimeAtUltimateConsignee" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="loadingDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="pickUpDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="releaseDateTimeOfSupplier" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="estimatedDeliveryPeriod" type="{urn:gs1:shared:shared_common:xsd:3}DateTimeRangeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DespatchInformationType", propOrder = {
    "actualShipDateTime",
    "despatchDateTime",
    "estimatedDeliveryDateTime",
    "estimatedDeliveryDateTimeAtUltimateConsignee",
    "loadingDateTime",
    "pickUpDateTime",
    "releaseDateTimeOfSupplier",
    "estimatedDeliveryPeriod"
})
public class DespatchInformationType {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar actualShipDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar despatchDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar estimatedDeliveryDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar estimatedDeliveryDateTimeAtUltimateConsignee;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar loadingDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar pickUpDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar releaseDateTimeOfSupplier;
    protected DateTimeRangeType estimatedDeliveryPeriod;

    /**
     * Gets the value of the actualShipDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActualShipDateTime() {
        return actualShipDateTime;
    }

    /**
     * Sets the value of the actualShipDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualShipDateTime(XMLGregorianCalendar value) {
        this.actualShipDateTime = value;
    }

    /**
     * Gets the value of the despatchDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDespatchDateTime() {
        return despatchDateTime;
    }

    /**
     * Sets the value of the despatchDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDespatchDateTime(XMLGregorianCalendar value) {
        this.despatchDateTime = value;
    }

    /**
     * Gets the value of the estimatedDeliveryDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEstimatedDeliveryDateTime() {
        return estimatedDeliveryDateTime;
    }

    /**
     * Sets the value of the estimatedDeliveryDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEstimatedDeliveryDateTime(XMLGregorianCalendar value) {
        this.estimatedDeliveryDateTime = value;
    }

    /**
     * Gets the value of the estimatedDeliveryDateTimeAtUltimateConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEstimatedDeliveryDateTimeAtUltimateConsignee() {
        return estimatedDeliveryDateTimeAtUltimateConsignee;
    }

    /**
     * Sets the value of the estimatedDeliveryDateTimeAtUltimateConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEstimatedDeliveryDateTimeAtUltimateConsignee(XMLGregorianCalendar value) {
        this.estimatedDeliveryDateTimeAtUltimateConsignee = value;
    }

    /**
     * Gets the value of the loadingDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLoadingDateTime() {
        return loadingDateTime;
    }

    /**
     * Sets the value of the loadingDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLoadingDateTime(XMLGregorianCalendar value) {
        this.loadingDateTime = value;
    }

    /**
     * Gets the value of the pickUpDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPickUpDateTime() {
        return pickUpDateTime;
    }

    /**
     * Sets the value of the pickUpDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPickUpDateTime(XMLGregorianCalendar value) {
        this.pickUpDateTime = value;
    }

    /**
     * Gets the value of the releaseDateTimeOfSupplier property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReleaseDateTimeOfSupplier() {
        return releaseDateTimeOfSupplier;
    }

    /**
     * Sets the value of the releaseDateTimeOfSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReleaseDateTimeOfSupplier(XMLGregorianCalendar value) {
        this.releaseDateTimeOfSupplier = value;
    }

    /**
     * Gets the value of the estimatedDeliveryPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeRangeType }
     *     
     */
    public DateTimeRangeType getEstimatedDeliveryPeriod() {
        return estimatedDeliveryPeriod;
    }

    /**
     * Sets the value of the estimatedDeliveryPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeRangeType }
     *     
     */
    public void setEstimatedDeliveryPeriod(DateTimeRangeType value) {
        this.estimatedDeliveryPeriod = value;
    }

}
