//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HandlingInstructionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HandlingInstructionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="handlingInstructionCode" type="{urn:gs1:ecom:ecom_common:xsd:3}HandlingInstructionCodeType" minOccurs="0"/>
 *         &lt;element name="handlingInstructionText" type="{urn:gs1:shared:shared_common:xsd:3}Description500Type" minOccurs="0"/>
 *         &lt;element name="printingInstructionCode" type="{urn:gs1:ecom:ecom_common:xsd:3}PrintingInstructionCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="storageTemperature" type="{urn:gs1:shared:shared_common:xsd:3}TemperatureRangeType" minOccurs="0"/>
 *         &lt;element name="transportTemperature" type="{urn:gs1:shared:shared_common:xsd:3}TemperatureRangeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HandlingInstructionType", propOrder = {
    "handlingInstructionCode",
    "handlingInstructionText",
    "printingInstructionCode",
    "storageTemperature",
    "transportTemperature"
})
public class HandlingInstructionType {

    protected HandlingInstructionCodeType handlingInstructionCode;
    protected Description500Type handlingInstructionText;
    protected List<PrintingInstructionCodeType> printingInstructionCode;
    protected TemperatureRangeType storageTemperature;
    protected TemperatureRangeType transportTemperature;

    /**
     * Gets the value of the handlingInstructionCode property.
     * 
     * @return
     *     possible object is
     *     {@link HandlingInstructionCodeType }
     *     
     */
    public HandlingInstructionCodeType getHandlingInstructionCode() {
        return handlingInstructionCode;
    }

    /**
     * Sets the value of the handlingInstructionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlingInstructionCodeType }
     *     
     */
    public void setHandlingInstructionCode(HandlingInstructionCodeType value) {
        this.handlingInstructionCode = value;
    }

    /**
     * Gets the value of the handlingInstructionText property.
     * 
     * @return
     *     possible object is
     *     {@link Description500Type }
     *     
     */
    public Description500Type getHandlingInstructionText() {
        return handlingInstructionText;
    }

    /**
     * Sets the value of the handlingInstructionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description500Type }
     *     
     */
    public void setHandlingInstructionText(Description500Type value) {
        this.handlingInstructionText = value;
    }

    /**
     * Gets the value of the printingInstructionCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the printingInstructionCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrintingInstructionCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrintingInstructionCodeType }
     * 
     * 
     */
    public List<PrintingInstructionCodeType> getPrintingInstructionCode() {
        if (printingInstructionCode == null) {
            printingInstructionCode = new ArrayList<PrintingInstructionCodeType>();
        }
        return this.printingInstructionCode;
    }

    /**
     * Gets the value of the storageTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link TemperatureRangeType }
     *     
     */
    public TemperatureRangeType getStorageTemperature() {
        return storageTemperature;
    }

    /**
     * Sets the value of the storageTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperatureRangeType }
     *     
     */
    public void setStorageTemperature(TemperatureRangeType value) {
        this.storageTemperature = value;
    }

    /**
     * Gets the value of the transportTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link TemperatureRangeType }
     *     
     */
    public TemperatureRangeType getTransportTemperature() {
        return transportTemperature;
    }

    /**
     * Sets the value of the transportTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperatureRangeType }
     *     
     */
    public void setTransportTemperature(TemperatureRangeType value) {
        this.transportTemperature = value;
    }

}
