//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InventoryStatusQuantitySpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InventoryStatusQuantitySpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inventoryStatusType" type="{urn:gs1:ecom:ecom_common:xsd:3}InventoryStatusCodeType"/>
 *         &lt;element name="quantityOfUnits" type="{urn:gs1:shared:shared_common:xsd:3}QuantityType"/>
 *         &lt;element name="transactionalItemData" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalItemDataType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InventoryStatusQuantitySpecificationType", propOrder = {
    "inventoryStatusType",
    "quantityOfUnits",
    "transactionalItemData"
})
public class InventoryStatusQuantitySpecificationType {

    @XmlElement(required = true)
    protected InventoryStatusCodeType inventoryStatusType;
    @XmlElement(required = true)
    protected QuantityType quantityOfUnits;
    protected List<TransactionalItemDataType> transactionalItemData;

    /**
     * Gets the value of the inventoryStatusType property.
     * 
     * @return
     *     possible object is
     *     {@link InventoryStatusCodeType }
     *     
     */
    public InventoryStatusCodeType getInventoryStatusType() {
        return inventoryStatusType;
    }

    /**
     * Sets the value of the inventoryStatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventoryStatusCodeType }
     *     
     */
    public void setInventoryStatusType(InventoryStatusCodeType value) {
        this.inventoryStatusType = value;
    }

    /**
     * Gets the value of the quantityOfUnits property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getQuantityOfUnits() {
        return quantityOfUnits;
    }

    /**
     * Sets the value of the quantityOfUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setQuantityOfUnits(QuantityType value) {
        this.quantityOfUnits = value;
    }

    /**
     * Gets the value of the transactionalItemData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transactionalItemData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransactionalItemData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionalItemDataType }
     * 
     * 
     */
    public List<TransactionalItemDataType> getTransactionalItemData() {
        if (transactionalItemData == null) {
            transactionalItemData = new ArrayList<TransactionalItemDataType>();
        }
        return this.transactionalItemData;
    }

}
