//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InventorySubLocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InventorySubLocationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gln" type="{urn:gs1:shared:shared_common:xsd:3}GLNType" minOccurs="0"/>
 *         &lt;element name="glnExtension" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="additionalPartyIdentification" type="{urn:gs1:shared:shared_common:xsd:3}AdditionalPartyIdentificationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="inventorySubLocationTypeCode" type="{urn:gs1:ecom:ecom_common:xsd:3}InventorySubLocationTypeCodeType" minOccurs="0"/>
 *         &lt;element name="inventorySubLocationFunctionCode" type="{urn:gs1:ecom:ecom_common:xsd:3}InventorySubLocationFunctionCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InventorySubLocationType", propOrder = {
    "gln",
    "glnExtension",
    "additionalPartyIdentification",
    "inventorySubLocationTypeCode",
    "inventorySubLocationFunctionCode"
})
public class InventorySubLocationType {

    protected String gln;
    protected String glnExtension;
    protected List<AdditionalPartyIdentificationType> additionalPartyIdentification;
    protected InventorySubLocationTypeCodeType inventorySubLocationTypeCode;
    protected List<InventorySubLocationFunctionCodeType> inventorySubLocationFunctionCode;

    /**
     * Gets the value of the gln property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGln() {
        return gln;
    }

    /**
     * Sets the value of the gln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGln(String value) {
        this.gln = value;
    }

    /**
     * Gets the value of the glnExtension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlnExtension() {
        return glnExtension;
    }

    /**
     * Sets the value of the glnExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlnExtension(String value) {
        this.glnExtension = value;
    }

    /**
     * Gets the value of the additionalPartyIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalPartyIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalPartyIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalPartyIdentificationType }
     * 
     * 
     */
    public List<AdditionalPartyIdentificationType> getAdditionalPartyIdentification() {
        if (additionalPartyIdentification == null) {
            additionalPartyIdentification = new ArrayList<AdditionalPartyIdentificationType>();
        }
        return this.additionalPartyIdentification;
    }

    /**
     * Gets the value of the inventorySubLocationTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link InventorySubLocationTypeCodeType }
     *     
     */
    public InventorySubLocationTypeCodeType getInventorySubLocationTypeCode() {
        return inventorySubLocationTypeCode;
    }

    /**
     * Sets the value of the inventorySubLocationTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventorySubLocationTypeCodeType }
     *     
     */
    public void setInventorySubLocationTypeCode(InventorySubLocationTypeCodeType value) {
        this.inventorySubLocationTypeCode = value;
    }

    /**
     * Gets the value of the inventorySubLocationFunctionCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inventorySubLocationFunctionCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInventorySubLocationFunctionCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InventorySubLocationFunctionCodeType }
     * 
     * 
     */
    public List<InventorySubLocationFunctionCodeType> getInventorySubLocationFunctionCode() {
        if (inventorySubLocationFunctionCode == null) {
            inventorySubLocationFunctionCode = new ArrayList<InventorySubLocationFunctionCodeType>();
        }
        return this.inventorySubLocationFunctionCode;
    }

}
