//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LeviedDutyFeeTaxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LeviedDutyFeeTaxType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dutyFeeTaxAccountingCurrency" type="{urn:gs1:shared:shared_common:xsd:3}CurrencyCodeType" minOccurs="0"/>
 *         &lt;element name="dutyFeeTaxAgencyName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dutyFeeTaxAmount" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="dutyFeeTaxAmountInAccountingCurrency" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="dutyFeeTaxBasisAmount" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="dutyFeeTaxBasisAmountInAccountingCurrency" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="dutyFeeTaxCategoryCode" type="{urn:gs1:shared:shared_common:xsd:3}TaxCategoryCodeType" minOccurs="0"/>
 *         &lt;element name="dutyFeeTaxDescription" type="{urn:gs1:shared:shared_common:xsd:3}Description80Type" minOccurs="0"/>
 *         &lt;element name="dutyFeeTaxExemptionDescription" type="{urn:gs1:shared:shared_common:xsd:3}Description80Type" minOccurs="0"/>
 *         &lt;element name="dutyFeeTaxPercentage" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="dutyFeeTaxPointDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="dutyFeeTaxTypeCode" type="{urn:gs1:ecom:ecom_common:xsd:3}DutyFeeTaxTypeCodeType" minOccurs="0"/>
 *         &lt;element name="extension" type="{urn:gs1:shared:shared_common:xsd:3}ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LeviedDutyFeeTaxType", propOrder = {
    "dutyFeeTaxAccountingCurrency",
    "dutyFeeTaxAgencyName",
    "dutyFeeTaxAmount",
    "dutyFeeTaxAmountInAccountingCurrency",
    "dutyFeeTaxBasisAmount",
    "dutyFeeTaxBasisAmountInAccountingCurrency",
    "dutyFeeTaxCategoryCode",
    "dutyFeeTaxDescription",
    "dutyFeeTaxExemptionDescription",
    "dutyFeeTaxPercentage",
    "dutyFeeTaxPointDate",
    "dutyFeeTaxTypeCode",
    "extension"
})
public class LeviedDutyFeeTaxType {

    protected CurrencyCodeType dutyFeeTaxAccountingCurrency;
    protected String dutyFeeTaxAgencyName;
    protected AmountType dutyFeeTaxAmount;
    protected AmountType dutyFeeTaxAmountInAccountingCurrency;
    protected AmountType dutyFeeTaxBasisAmount;
    protected AmountType dutyFeeTaxBasisAmountInAccountingCurrency;
    protected TaxCategoryCodeType dutyFeeTaxCategoryCode;
    protected Description80Type dutyFeeTaxDescription;
    protected Description80Type dutyFeeTaxExemptionDescription;
    protected Float dutyFeeTaxPercentage;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dutyFeeTaxPointDate;
    protected DutyFeeTaxTypeCodeType dutyFeeTaxTypeCode;
    protected ExtensionType extension;

    /**
     * Gets the value of the dutyFeeTaxAccountingCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getDutyFeeTaxAccountingCurrency() {
        return dutyFeeTaxAccountingCurrency;
    }

    /**
     * Sets the value of the dutyFeeTaxAccountingCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setDutyFeeTaxAccountingCurrency(CurrencyCodeType value) {
        this.dutyFeeTaxAccountingCurrency = value;
    }

    /**
     * Gets the value of the dutyFeeTaxAgencyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDutyFeeTaxAgencyName() {
        return dutyFeeTaxAgencyName;
    }

    /**
     * Sets the value of the dutyFeeTaxAgencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDutyFeeTaxAgencyName(String value) {
        this.dutyFeeTaxAgencyName = value;
    }

    /**
     * Gets the value of the dutyFeeTaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getDutyFeeTaxAmount() {
        return dutyFeeTaxAmount;
    }

    /**
     * Sets the value of the dutyFeeTaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setDutyFeeTaxAmount(AmountType value) {
        this.dutyFeeTaxAmount = value;
    }

    /**
     * Gets the value of the dutyFeeTaxAmountInAccountingCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getDutyFeeTaxAmountInAccountingCurrency() {
        return dutyFeeTaxAmountInAccountingCurrency;
    }

    /**
     * Sets the value of the dutyFeeTaxAmountInAccountingCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setDutyFeeTaxAmountInAccountingCurrency(AmountType value) {
        this.dutyFeeTaxAmountInAccountingCurrency = value;
    }

    /**
     * Gets the value of the dutyFeeTaxBasisAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getDutyFeeTaxBasisAmount() {
        return dutyFeeTaxBasisAmount;
    }

    /**
     * Sets the value of the dutyFeeTaxBasisAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setDutyFeeTaxBasisAmount(AmountType value) {
        this.dutyFeeTaxBasisAmount = value;
    }

    /**
     * Gets the value of the dutyFeeTaxBasisAmountInAccountingCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getDutyFeeTaxBasisAmountInAccountingCurrency() {
        return dutyFeeTaxBasisAmountInAccountingCurrency;
    }

    /**
     * Sets the value of the dutyFeeTaxBasisAmountInAccountingCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setDutyFeeTaxBasisAmountInAccountingCurrency(AmountType value) {
        this.dutyFeeTaxBasisAmountInAccountingCurrency = value;
    }

    /**
     * Gets the value of the dutyFeeTaxCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link TaxCategoryCodeType }
     *     
     */
    public TaxCategoryCodeType getDutyFeeTaxCategoryCode() {
        return dutyFeeTaxCategoryCode;
    }

    /**
     * Sets the value of the dutyFeeTaxCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxCategoryCodeType }
     *     
     */
    public void setDutyFeeTaxCategoryCode(TaxCategoryCodeType value) {
        this.dutyFeeTaxCategoryCode = value;
    }

    /**
     * Gets the value of the dutyFeeTaxDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Description80Type }
     *     
     */
    public Description80Type getDutyFeeTaxDescription() {
        return dutyFeeTaxDescription;
    }

    /**
     * Sets the value of the dutyFeeTaxDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description80Type }
     *     
     */
    public void setDutyFeeTaxDescription(Description80Type value) {
        this.dutyFeeTaxDescription = value;
    }

    /**
     * Gets the value of the dutyFeeTaxExemptionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Description80Type }
     *     
     */
    public Description80Type getDutyFeeTaxExemptionDescription() {
        return dutyFeeTaxExemptionDescription;
    }

    /**
     * Sets the value of the dutyFeeTaxExemptionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description80Type }
     *     
     */
    public void setDutyFeeTaxExemptionDescription(Description80Type value) {
        this.dutyFeeTaxExemptionDescription = value;
    }

    /**
     * Gets the value of the dutyFeeTaxPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDutyFeeTaxPercentage() {
        return dutyFeeTaxPercentage;
    }

    /**
     * Sets the value of the dutyFeeTaxPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDutyFeeTaxPercentage(Float value) {
        this.dutyFeeTaxPercentage = value;
    }

    /**
     * Gets the value of the dutyFeeTaxPointDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDutyFeeTaxPointDate() {
        return dutyFeeTaxPointDate;
    }

    /**
     * Sets the value of the dutyFeeTaxPointDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDutyFeeTaxPointDate(XMLGregorianCalendar value) {
        this.dutyFeeTaxPointDate = value;
    }

    /**
     * Gets the value of the dutyFeeTaxTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link DutyFeeTaxTypeCodeType }
     *     
     */
    public DutyFeeTaxTypeCodeType getDutyFeeTaxTypeCode() {
        return dutyFeeTaxTypeCode;
    }

    /**
     * Sets the value of the dutyFeeTaxTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DutyFeeTaxTypeCodeType }
     *     
     */
    public void setDutyFeeTaxTypeCode(DutyFeeTaxTypeCodeType value) {
        this.dutyFeeTaxTypeCode = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setExtension(ExtensionType value) {
        this.extension = value;
    }

}
