//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LogisticEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogisticEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="logisticEventTypeCode" type="{urn:gs1:ecom:ecom_common:xsd:3}LogisticEventTypeCodeType" minOccurs="0"/>
 *         &lt;element name="logisticEventDuration" type="{urn:gs1:shared:shared_common:xsd:3}TimeMeasurementType" minOccurs="0"/>
 *         &lt;element name="logisticLocation" type="{urn:gs1:ecom:ecom_common:xsd:3}LogisticLocationType" minOccurs="0"/>
 *         &lt;element name="logisticEventPeriod" type="{urn:gs1:shared:shared_common:xsd:3}DateTimeRangeType" minOccurs="0"/>
 *         &lt;element name="logisticEventDateTime" type="{urn:gs1:shared:shared_common:xsd:3}DateOptionalTimeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogisticEventType", propOrder = {
    "logisticEventTypeCode",
    "logisticEventDuration",
    "logisticLocation",
    "logisticEventPeriod",
    "logisticEventDateTime"
})
public class LogisticEventType {

    protected LogisticEventTypeCodeType logisticEventTypeCode;
    protected TimeMeasurementType logisticEventDuration;
    protected LogisticLocationType logisticLocation;
    protected DateTimeRangeType logisticEventPeriod;
    protected DateOptionalTimeType logisticEventDateTime;

    /**
     * Gets the value of the logisticEventTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link LogisticEventTypeCodeType }
     *     
     */
    public LogisticEventTypeCodeType getLogisticEventTypeCode() {
        return logisticEventTypeCode;
    }

    /**
     * Sets the value of the logisticEventTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogisticEventTypeCodeType }
     *     
     */
    public void setLogisticEventTypeCode(LogisticEventTypeCodeType value) {
        this.logisticEventTypeCode = value;
    }

    /**
     * Gets the value of the logisticEventDuration property.
     * 
     * @return
     *     possible object is
     *     {@link TimeMeasurementType }
     *     
     */
    public TimeMeasurementType getLogisticEventDuration() {
        return logisticEventDuration;
    }

    /**
     * Sets the value of the logisticEventDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeMeasurementType }
     *     
     */
    public void setLogisticEventDuration(TimeMeasurementType value) {
        this.logisticEventDuration = value;
    }

    /**
     * Gets the value of the logisticLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LogisticLocationType }
     *     
     */
    public LogisticLocationType getLogisticLocation() {
        return logisticLocation;
    }

    /**
     * Sets the value of the logisticLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogisticLocationType }
     *     
     */
    public void setLogisticLocation(LogisticLocationType value) {
        this.logisticLocation = value;
    }

    /**
     * Gets the value of the logisticEventPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeRangeType }
     *     
     */
    public DateTimeRangeType getLogisticEventPeriod() {
        return logisticEventPeriod;
    }

    /**
     * Sets the value of the logisticEventPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeRangeType }
     *     
     */
    public void setLogisticEventPeriod(DateTimeRangeType value) {
        this.logisticEventPeriod = value;
    }

    /**
     * Gets the value of the logisticEventDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateOptionalTimeType }
     *     
     */
    public DateOptionalTimeType getLogisticEventDateTime() {
        return logisticEventDateTime;
    }

    /**
     * Sets the value of the logisticEventDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateOptionalTimeType }
     *     
     */
    public void setLogisticEventDateTime(DateOptionalTimeType value) {
        this.logisticEventDateTime = value;
    }

}
