//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LogisticLocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogisticLocationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unLocationCode" type="{urn:gs1:ecom:ecom_common:xsd:3}UNLocationCodeType" minOccurs="0"/>
 *         &lt;element name="gln" type="{urn:gs1:shared:shared_common:xsd:3}GLNType" minOccurs="0"/>
 *         &lt;element name="additionalLocationIdentification" type="{urn:gs1:shared:shared_common:xsd:3}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sublocationIdentification" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="locationName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="locationSpecificInstructions" type="{urn:gs1:shared:shared_common:xsd:3}Description200Type" minOccurs="0"/>
 *         &lt;element name="utcOffset" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="address" type="{urn:gs1:shared:shared_common:xsd:3}AddressType" minOccurs="0"/>
 *         &lt;element name="contact" type="{urn:gs1:shared:shared_common:xsd:3}ContactType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="regularOperatingHours" type="{urn:gs1:ecom:ecom_common:xsd:3}OperatingHoursType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="specialOperatingHours" type="{urn:gs1:ecom:ecom_common:xsd:3}SpecialOperatingHoursType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogisticLocationType", propOrder = {
    "unLocationCode",
    "gln",
    "additionalLocationIdentification",
    "sublocationIdentification",
    "locationName",
    "locationSpecificInstructions",
    "utcOffset",
    "address",
    "contact",
    "regularOperatingHours",
    "specialOperatingHours"
})
public class LogisticLocationType {

    protected UNLocationCodeType unLocationCode;
    protected String gln;
    protected List<IdentifierType> additionalLocationIdentification;
    protected String sublocationIdentification;
    protected String locationName;
    protected Description200Type locationSpecificInstructions;
    protected Float utcOffset;
    protected AddressType address;
    protected List<ContactType> contact;
    protected List<OperatingHoursType> regularOperatingHours;
    protected List<SpecialOperatingHoursType> specialOperatingHours;

    /**
     * Gets the value of the unLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link UNLocationCodeType }
     *     
     */
    public UNLocationCodeType getUnLocationCode() {
        return unLocationCode;
    }

    /**
     * Sets the value of the unLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link UNLocationCodeType }
     *     
     */
    public void setUnLocationCode(UNLocationCodeType value) {
        this.unLocationCode = value;
    }

    /**
     * Gets the value of the gln property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGln() {
        return gln;
    }

    /**
     * Sets the value of the gln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGln(String value) {
        this.gln = value;
    }

    /**
     * Gets the value of the additionalLocationIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalLocationIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalLocationIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getAdditionalLocationIdentification() {
        if (additionalLocationIdentification == null) {
            additionalLocationIdentification = new ArrayList<IdentifierType>();
        }
        return this.additionalLocationIdentification;
    }

    /**
     * Gets the value of the sublocationIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSublocationIdentification() {
        return sublocationIdentification;
    }

    /**
     * Sets the value of the sublocationIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSublocationIdentification(String value) {
        this.sublocationIdentification = value;
    }

    /**
     * Gets the value of the locationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * Sets the value of the locationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationName(String value) {
        this.locationName = value;
    }

    /**
     * Gets the value of the locationSpecificInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link Description200Type }
     *     
     */
    public Description200Type getLocationSpecificInstructions() {
        return locationSpecificInstructions;
    }

    /**
     * Sets the value of the locationSpecificInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description200Type }
     *     
     */
    public void setLocationSpecificInstructions(Description200Type value) {
        this.locationSpecificInstructions = value;
    }

    /**
     * Gets the value of the utcOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getUtcOffset() {
        return utcOffset;
    }

    /**
     * Sets the value of the utcOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setUtcOffset(Float value) {
        this.utcOffset = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactType }
     * 
     * 
     */
    public List<ContactType> getContact() {
        if (contact == null) {
            contact = new ArrayList<ContactType>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the regularOperatingHours property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regularOperatingHours property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegularOperatingHours().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperatingHoursType }
     * 
     * 
     */
    public List<OperatingHoursType> getRegularOperatingHours() {
        if (regularOperatingHours == null) {
            regularOperatingHours = new ArrayList<OperatingHoursType>();
        }
        return this.regularOperatingHours;
    }

    /**
     * Gets the value of the specialOperatingHours property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialOperatingHours property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialOperatingHours().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecialOperatingHoursType }
     * 
     * 
     */
    public List<SpecialOperatingHoursType> getSpecialOperatingHours() {
        if (specialOperatingHours == null) {
            specialOperatingHours = new ArrayList<SpecialOperatingHoursType>();
        }
        return this.specialOperatingHours;
    }

}
