//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.artworkcontent.gs1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ScopeInformation_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "ScopeInformation");
    private final static QName _CorrelationInformation_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "CorrelationInformation");
    private final static QName _StandardBusinessDocumentHeader_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "StandardBusinessDocumentHeader");
    private final static QName _BusinessService_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "BusinessService");
    private final static QName _StandardBusinessDocument_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "StandardBusinessDocument");
    private final static QName _ArtworkContentMessage_QNAME = new QName("urn:gs1:ecom:artwork_content:xsd:3", "artworkContentMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.artworkcontent.gs1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArtworkContentMessageType }
     * 
     */
    public ArtworkContentMessageType createArtworkContentMessageType() {
        return new ArtworkContentMessageType();
    }

    /**
     * Create an instance of {@link ArtworkContentType }
     * 
     */
    public ArtworkContentType createArtworkContentType() {
        return new ArtworkContentType();
    }

    /**
     * Create an instance of {@link StandardBusinessDocumentHeader }
     * 
     */
    public StandardBusinessDocumentHeader createStandardBusinessDocumentHeader() {
        return new StandardBusinessDocumentHeader();
    }

    /**
     * Create an instance of {@link CorrelationInformation }
     * 
     */
    public CorrelationInformation createCorrelationInformation() {
        return new CorrelationInformation();
    }

    /**
     * Create an instance of {@link StandardBusinessDocument }
     * 
     */
    public StandardBusinessDocument createStandardBusinessDocument() {
        return new StandardBusinessDocument();
    }

    /**
     * Create an instance of {@link BusinessService }
     * 
     */
    public BusinessService createBusinessService() {
        return new BusinessService();
    }

    /**
     * Create an instance of {@link ManifestItem }
     * 
     */
    public ManifestItem createManifestItem() {
        return new ManifestItem();
    }

    /**
     * Create an instance of {@link ServiceTransaction }
     * 
     */
    public ServiceTransaction createServiceTransaction() {
        return new ServiceTransaction();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link DocumentIdentification }
     * 
     */
    public DocumentIdentification createDocumentIdentification() {
        return new DocumentIdentification();
    }

    /**
     * Create an instance of {@link PartnerIdentification }
     * 
     */
    public PartnerIdentification createPartnerIdentification() {
        return new PartnerIdentification();
    }

    /**
     * Create an instance of {@link Partner }
     * 
     */
    public Partner createPartner() {
        return new Partner();
    }

    /**
     * Create an instance of {@link BusinessScope }
     * 
     */
    public BusinessScope createBusinessScope() {
        return new BusinessScope();
    }

    /**
     * Create an instance of {@link Scope }
     * 
     */
    public Scope createScope() {
        return new Scope();
    }

    /**
     * Create an instance of {@link Description2500Type }
     * 
     */
    public Description2500Type createDescription2500Type() {
        return new Description2500Type();
    }

    /**
     * Create an instance of {@link AmountRangeType }
     * 
     */
    public AmountRangeType createAmountRangeType() {
        return new AmountRangeType();
    }

    /**
     * Create an instance of {@link IncotermsCodeType }
     * 
     */
    public IncotermsCodeType createIncotermsCodeType() {
        return new IncotermsCodeType();
    }

    /**
     * Create an instance of {@link TimeMeasurementUnitCodeType }
     * 
     */
    public TimeMeasurementUnitCodeType createTimeMeasurementUnitCodeType() {
        return new TimeMeasurementUnitCodeType();
    }

    /**
     * Create an instance of {@link SizeType }
     * 
     */
    public SizeType createSizeType() {
        return new SizeType();
    }

    /**
     * Create an instance of {@link StringRangeType }
     * 
     */
    public StringRangeType createStringRangeType() {
        return new StringRangeType();
    }

    /**
     * Create an instance of {@link Description80Type }
     * 
     */
    public Description80Type createDescription80Type() {
        return new Description80Type();
    }

    /**
     * Create an instance of {@link LogisticUnitIdentificationType }
     * 
     */
    public LogisticUnitIdentificationType createLogisticUnitIdentificationType() {
        return new LogisticUnitIdentificationType();
    }

    /**
     * Create an instance of {@link Description5000Type }
     * 
     */
    public Description5000Type createDescription5000Type() {
        return new Description5000Type();
    }

    /**
     * Create an instance of {@link RangeType }
     * 
     */
    public RangeType createRangeType() {
        return new RangeType();
    }

    /**
     * Create an instance of {@link CurrencyExchangeRateInformationType }
     * 
     */
    public CurrencyExchangeRateInformationType createCurrencyExchangeRateInformationType() {
        return new CurrencyExchangeRateInformationType();
    }

    /**
     * Create an instance of {@link DimensionType }
     * 
     */
    public DimensionType createDimensionType() {
        return new DimensionType();
    }

    /**
     * Create an instance of {@link AdditionalLogisticUnitIdentificationType }
     * 
     */
    public AdditionalLogisticUnitIdentificationType createAdditionalLogisticUnitIdentificationType() {
        return new AdditionalLogisticUnitIdentificationType();
    }

    /**
     * Create an instance of {@link IndividualAssetIdentificationType }
     * 
     */
    public IndividualAssetIdentificationType createIndividualAssetIdentificationType() {
        return new IndividualAssetIdentificationType();
    }

    /**
     * Create an instance of {@link PartyIdentificationType }
     * 
     */
    public PartyIdentificationType createPartyIdentificationType() {
        return new PartyIdentificationType();
    }

    /**
     * Create an instance of {@link EntityIdentificationType }
     * 
     */
    public EntityIdentificationType createEntityIdentificationType() {
        return new EntityIdentificationType();
    }

    /**
     * Create an instance of {@link GeographicalCoordinatesType }
     * 
     */
    public GeographicalCoordinatesType createGeographicalCoordinatesType() {
        return new GeographicalCoordinatesType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link ServiceRelationIdentificationType }
     * 
     */
    public ServiceRelationIdentificationType createServiceRelationIdentificationType() {
        return new ServiceRelationIdentificationType();
    }

    /**
     * Create an instance of {@link AdditionalIndividualAssetIdentificationType }
     * 
     */
    public AdditionalIndividualAssetIdentificationType createAdditionalIndividualAssetIdentificationType() {
        return new AdditionalIndividualAssetIdentificationType();
    }

    /**
     * Create an instance of {@link BarCodeTypeCodeType }
     * 
     */
    public BarCodeTypeCodeType createBarCodeTypeCodeType() {
        return new BarCodeTypeCodeType();
    }

    /**
     * Create an instance of {@link AdditionalConsignmentIdentificationTypeCodeType }
     * 
     */
    public AdditionalConsignmentIdentificationTypeCodeType createAdditionalConsignmentIdentificationTypeCodeType() {
        return new AdditionalConsignmentIdentificationTypeCodeType();
    }

    /**
     * Create an instance of {@link AdditionalTradeItemIdentificationType }
     * 
     */
    public AdditionalTradeItemIdentificationType createAdditionalTradeItemIdentificationType() {
        return new AdditionalTradeItemIdentificationType();
    }

    /**
     * Create an instance of {@link ConsignmentIdentificationType }
     * 
     */
    public ConsignmentIdentificationType createConsignmentIdentificationType() {
        return new ConsignmentIdentificationType();
    }

    /**
     * Create an instance of {@link MultiDescription70Type }
     * 
     */
    public MultiDescription70Type createMultiDescription70Type() {
        return new MultiDescription70Type();
    }

    /**
     * Create an instance of {@link TemperatureRangeType }
     * 
     */
    public TemperatureRangeType createTemperatureRangeType() {
        return new TemperatureRangeType();
    }

    /**
     * Create an instance of {@link LanguageCodeType }
     * 
     */
    public LanguageCodeType createLanguageCodeType() {
        return new LanguageCodeType();
    }

    /**
     * Create an instance of {@link AdditionalShipmentIdentificationTypeCodeType }
     * 
     */
    public AdditionalShipmentIdentificationTypeCodeType createAdditionalShipmentIdentificationTypeCodeType() {
        return new AdditionalShipmentIdentificationTypeCodeType();
    }

    /**
     * Create an instance of {@link AdditionalPartyIdentificationTypeCodeType }
     * 
     */
    public AdditionalPartyIdentificationTypeCodeType createAdditionalPartyIdentificationTypeCodeType() {
        return new AdditionalPartyIdentificationTypeCodeType();
    }

    /**
     * Create an instance of {@link AdditionalTradeItemIdentificationTypeCodeType }
     * 
     */
    public AdditionalTradeItemIdentificationTypeCodeType createAdditionalTradeItemIdentificationTypeCodeType() {
        return new AdditionalTradeItemIdentificationTypeCodeType();
    }

    /**
     * Create an instance of {@link CommunicationChannelType }
     * 
     */
    public CommunicationChannelType createCommunicationChannelType() {
        return new CommunicationChannelType();
    }

    /**
     * Create an instance of {@link Description35Type }
     * 
     */
    public Description35Type createDescription35Type() {
        return new Description35Type();
    }

    /**
     * Create an instance of {@link MeasurementUnitCodeType }
     * 
     */
    public MeasurementUnitCodeType createMeasurementUnitCodeType() {
        return new MeasurementUnitCodeType();
    }

    /**
     * Create an instance of {@link ContactTypeCodeType }
     * 
     */
    public ContactTypeCodeType createContactTypeCodeType() {
        return new ContactTypeCodeType();
    }

    /**
     * Create an instance of {@link MeasurementType }
     * 
     */
    public MeasurementType createMeasurementType() {
        return new MeasurementType();
    }

    /**
     * Create an instance of {@link CountrySubdivisionCodeType }
     * 
     */
    public CountrySubdivisionCodeType createCountrySubdivisionCodeType() {
        return new CountrySubdivisionCodeType();
    }

    /**
     * Create an instance of {@link AdditionalReturnableAssetIdentificationType }
     * 
     */
    public AdditionalReturnableAssetIdentificationType createAdditionalReturnableAssetIdentificationType() {
        return new AdditionalReturnableAssetIdentificationType();
    }

    /**
     * Create an instance of {@link SizeCodeType }
     * 
     */
    public SizeCodeType createSizeCodeType() {
        return new SizeCodeType();
    }

    /**
     * Create an instance of {@link DateTimeRangeType }
     * 
     */
    public DateTimeRangeType createDateTimeRangeType() {
        return new DateTimeRangeType();
    }

    /**
     * Create an instance of {@link PartyRoleCodeType }
     * 
     */
    public PartyRoleCodeType createPartyRoleCodeType() {
        return new PartyRoleCodeType();
    }

    /**
     * Create an instance of {@link TradeItemIdentificationType }
     * 
     */
    public TradeItemIdentificationType createTradeItemIdentificationType() {
        return new TradeItemIdentificationType();
    }

    /**
     * Create an instance of {@link AdditionalIndividualAssetIdentificationTypeCodeType }
     * 
     */
    public AdditionalIndividualAssetIdentificationTypeCodeType createAdditionalIndividualAssetIdentificationTypeCodeType() {
        return new AdditionalIndividualAssetIdentificationTypeCodeType();
    }

    /**
     * Create an instance of {@link DateFormatCodeType }
     * 
     */
    public DateFormatCodeType createDateFormatCodeType() {
        return new DateFormatCodeType();
    }

    /**
     * Create an instance of {@link Description500Type }
     * 
     */
    public Description500Type createDescription500Type() {
        return new Description500Type();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link CommunicationChannelCodeType }
     * 
     */
    public CommunicationChannelCodeType createCommunicationChannelCodeType() {
        return new CommunicationChannelCodeType();
    }

    /**
     * Create an instance of {@link ColourCodeType }
     * 
     */
    public ColourCodeType createColourCodeType() {
        return new ColourCodeType();
    }

    /**
     * Create an instance of {@link TemperatureMeasurementUnitCodeType }
     * 
     */
    public TemperatureMeasurementUnitCodeType createTemperatureMeasurementUnitCodeType() {
        return new TemperatureMeasurementUnitCodeType();
    }

    /**
     * Create an instance of {@link ResponsibleAgencyCodeType }
     * 
     */
    public ResponsibleAgencyCodeType createResponsibleAgencyCodeType() {
        return new ResponsibleAgencyCodeType();
    }

    /**
     * Create an instance of {@link ShipmentIdentificationType }
     * 
     */
    public ShipmentIdentificationType createShipmentIdentificationType() {
        return new ShipmentIdentificationType();
    }

    /**
     * Create an instance of {@link ReturnableAssetIdentificationType }
     * 
     */
    public ReturnableAssetIdentificationType createReturnableAssetIdentificationType() {
        return new ReturnableAssetIdentificationType();
    }

    /**
     * Create an instance of {@link TimeMeasurementType }
     * 
     */
    public TimeMeasurementType createTimeMeasurementType() {
        return new TimeMeasurementType();
    }

    /**
     * Create an instance of {@link AdditionalServiceRelationIdentificationType }
     * 
     */
    public AdditionalServiceRelationIdentificationType createAdditionalServiceRelationIdentificationType() {
        return new AdditionalServiceRelationIdentificationType();
    }

    /**
     * Create an instance of {@link NutrientTypeCodeType }
     * 
     */
    public NutrientTypeCodeType createNutrientTypeCodeType() {
        return new NutrientTypeCodeType();
    }

    /**
     * Create an instance of {@link DateOptionalTimeType }
     * 
     */
    public DateOptionalTimeType createDateOptionalTimeType() {
        return new DateOptionalTimeType();
    }

    /**
     * Create an instance of {@link AdditionalServiceRelationIdentificationTypeCodeType }
     * 
     */
    public AdditionalServiceRelationIdentificationTypeCodeType createAdditionalServiceRelationIdentificationTypeCodeType() {
        return new AdditionalServiceRelationIdentificationTypeCodeType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link AdditionalLogisticUnitIdentificationTypeCodeType }
     * 
     */
    public AdditionalLogisticUnitIdentificationTypeCodeType createAdditionalLogisticUnitIdentificationTypeCodeType() {
        return new AdditionalLogisticUnitIdentificationTypeCodeType();
    }

    /**
     * Create an instance of {@link CurrencyCodeType }
     * 
     */
    public CurrencyCodeType createCurrencyCodeType() {
        return new CurrencyCodeType();
    }

    /**
     * Create an instance of {@link PaymentTermsTypeCodeType }
     * 
     */
    public PaymentTermsTypeCodeType createPaymentTermsTypeCodeType() {
        return new PaymentTermsTypeCodeType();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link TradeItemClassificationType }
     * 
     */
    public TradeItemClassificationType createTradeItemClassificationType() {
        return new TradeItemClassificationType();
    }

    /**
     * Create an instance of {@link TaxCategoryCodeType }
     * 
     */
    public TaxCategoryCodeType createTaxCategoryCodeType() {
        return new TaxCategoryCodeType();
    }

    /**
     * Create an instance of {@link TargetMarketType }
     * 
     */
    public TargetMarketType createTargetMarketType() {
        return new TargetMarketType();
    }

    /**
     * Create an instance of {@link EntityTypeCodeType }
     * 
     */
    public EntityTypeCodeType createEntityTypeCodeType() {
        return new EntityTypeCodeType();
    }

    /**
     * Create an instance of {@link AdditionalConsignmentIdentificationType }
     * 
     */
    public AdditionalConsignmentIdentificationType createAdditionalConsignmentIdentificationType() {
        return new AdditionalConsignmentIdentificationType();
    }

    /**
     * Create an instance of {@link Description200Type }
     * 
     */
    public Description200Type createDescription200Type() {
        return new Description200Type();
    }

    /**
     * Create an instance of {@link AdditionalTradeItemClassificationCodeType }
     * 
     */
    public AdditionalTradeItemClassificationCodeType createAdditionalTradeItemClassificationCodeType() {
        return new AdditionalTradeItemClassificationCodeType();
    }

    /**
     * Create an instance of {@link AllowanceChargeTypeCodeType }
     * 
     */
    public AllowanceChargeTypeCodeType createAllowanceChargeTypeCodeType() {
        return new AllowanceChargeTypeCodeType();
    }

    /**
     * Create an instance of {@link QuantityRangeType }
     * 
     */
    public QuantityRangeType createQuantityRangeType() {
        return new QuantityRangeType();
    }

    /**
     * Create an instance of {@link Description1000Type }
     * 
     */
    public Description1000Type createDescription1000Type() {
        return new Description1000Type();
    }

    /**
     * Create an instance of {@link Description70Type }
     * 
     */
    public Description70Type createDescription70Type() {
        return new Description70Type();
    }

    /**
     * Create an instance of {@link GPCAttributeType }
     * 
     */
    public GPCAttributeType createGPCAttributeType() {
        return new GPCAttributeType();
    }

    /**
     * Create an instance of {@link PaymentTimePeriodType }
     * 
     */
    public PaymentTimePeriodType createPaymentTimePeriodType() {
        return new PaymentTimePeriodType();
    }

    /**
     * Create an instance of {@link FinancialRoutingNumberType }
     * 
     */
    public FinancialRoutingNumberType createFinancialRoutingNumberType() {
        return new FinancialRoutingNumberType();
    }

    /**
     * Create an instance of {@link DocumentReferenceType }
     * 
     */
    public DocumentReferenceType createDocumentReferenceType() {
        return new DocumentReferenceType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link FinancialAccountType }
     * 
     */
    public FinancialAccountType createFinancialAccountType() {
        return new FinancialAccountType();
    }

    /**
     * Create an instance of {@link FinancialAccountNumberTypeCodeType }
     * 
     */
    public FinancialAccountNumberTypeCodeType createFinancialAccountNumberTypeCodeType() {
        return new FinancialAccountNumberTypeCodeType();
    }

    /**
     * Create an instance of {@link TemperatureMeasurementType }
     * 
     */
    public TemperatureMeasurementType createTemperatureMeasurementType() {
        return new TemperatureMeasurementType();
    }

    /**
     * Create an instance of {@link FinancialRoutingNumberTypeCodeType }
     * 
     */
    public FinancialRoutingNumberTypeCodeType createFinancialRoutingNumberTypeCodeType() {
        return new FinancialRoutingNumberTypeCodeType();
    }

    /**
     * Create an instance of {@link PaymentMethodCodeType }
     * 
     */
    public PaymentMethodCodeType createPaymentMethodCodeType() {
        return new PaymentMethodCodeType();
    }

    /**
     * Create an instance of {@link AdditionalShipmentIdentificationType }
     * 
     */
    public AdditionalShipmentIdentificationType createAdditionalShipmentIdentificationType() {
        return new AdditionalShipmentIdentificationType();
    }

    /**
     * Create an instance of {@link TypedEntityIdentificationType }
     * 
     */
    public TypedEntityIdentificationType createTypedEntityIdentificationType() {
        return new TypedEntityIdentificationType();
    }

    /**
     * Create an instance of {@link ColourType }
     * 
     */
    public ColourType createColourType() {
        return new ColourType();
    }

    /**
     * Create an instance of {@link CountryCodeType }
     * 
     */
    public CountryCodeType createCountryCodeType() {
        return new CountryCodeType();
    }

    /**
     * Create an instance of {@link AdditionalReturnableAssetIdentificationTypeCodeType }
     * 
     */
    public AdditionalReturnableAssetIdentificationTypeCodeType createAdditionalReturnableAssetIdentificationTypeCodeType() {
        return new AdditionalReturnableAssetIdentificationTypeCodeType();
    }

    /**
     * Create an instance of {@link AdditionalPartyIdentificationType }
     * 
     */
    public AdditionalPartyIdentificationType createAdditionalPartyIdentificationType() {
        return new AdditionalPartyIdentificationType();
    }

    /**
     * Create an instance of {@link MeasurementRangeType }
     * 
     */
    public MeasurementRangeType createMeasurementRangeType() {
        return new MeasurementRangeType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link GS1CodeType }
     * 
     */
    public GS1CodeType createGS1CodeType() {
        return new GS1CodeType();
    }

    /**
     * Create an instance of {@link ArtworkContentTechnicalDrawingType }
     * 
     */
    public ArtworkContentTechnicalDrawingType createArtworkContentTechnicalDrawingType() {
        return new ArtworkContentTechnicalDrawingType();
    }

    /**
     * Create an instance of {@link ArtworkContentLocaleType }
     * 
     */
    public ArtworkContentLocaleType createArtworkContentLocaleType() {
        return new ArtworkContentLocaleType();
    }

    /**
     * Create an instance of {@link CopyElementTypeCodeType }
     * 
     */
    public CopyElementTypeCodeType createCopyElementTypeCodeType() {
        return new CopyElementTypeCodeType();
    }

    /**
     * Create an instance of {@link GraphicElementTypeCodeType }
     * 
     */
    public GraphicElementTypeCodeType createGraphicElementTypeCodeType() {
        return new GraphicElementTypeCodeType();
    }

    /**
     * Create an instance of {@link ArtworkContentCopyElementType }
     * 
     */
    public ArtworkContentCopyElementType createArtworkContentCopyElementType() {
        return new ArtworkContentCopyElementType();
    }

    /**
     * Create an instance of {@link ArtworkContentResponseStatusType }
     * 
     */
    public ArtworkContentResponseStatusType createArtworkContentResponseStatusType() {
        return new ArtworkContentResponseStatusType();
    }

    /**
     * Create an instance of {@link ArtworkContentDataCarrierElementType }
     * 
     */
    public ArtworkContentDataCarrierElementType createArtworkContentDataCarrierElementType() {
        return new ArtworkContentDataCarrierElementType();
    }

    /**
     * Create an instance of {@link DataCarrierElementTypeCodeType }
     * 
     */
    public DataCarrierElementTypeCodeType createDataCarrierElementTypeCodeType() {
        return new DataCarrierElementTypeCodeType();
    }

    /**
     * Create an instance of {@link ArtworkContentDataCarrierDetailType }
     * 
     */
    public ArtworkContentDataCarrierDetailType createArtworkContentDataCarrierDetailType() {
        return new ArtworkContentDataCarrierDetailType();
    }

    /**
     * Create an instance of {@link StructuredCopyElementTypeCodeType }
     * 
     */
    public StructuredCopyElementTypeCodeType createStructuredCopyElementTypeCodeType() {
        return new StructuredCopyElementTypeCodeType();
    }

    /**
     * Create an instance of {@link ArtworkContentStructuredCopyElementType }
     * 
     */
    public ArtworkContentStructuredCopyElementType createArtworkContentStructuredCopyElementType() {
        return new ArtworkContentStructuredCopyElementType();
    }

    /**
     * Create an instance of {@link ArtworkContentPieceOfArtType }
     * 
     */
    public ArtworkContentPieceOfArtType createArtworkContentPieceOfArtType() {
        return new ArtworkContentPieceOfArtType();
    }

    /**
     * Create an instance of {@link ArtworkContentGraphicElementType }
     * 
     */
    public ArtworkContentGraphicElementType createArtworkContentGraphicElementType() {
        return new ArtworkContentGraphicElementType();
    }

    /**
     * Create an instance of {@link XHTMLType }
     * 
     */
    public XHTMLType createXHTMLType() {
        return new XHTMLType();
    }

    /**
     * Create an instance of {@link InventoryActivityTypeCodeType }
     * 
     */
    public InventoryActivityTypeCodeType createInventoryActivityTypeCodeType() {
        return new InventoryActivityTypeCodeType();
    }

    /**
     * Create an instance of {@link DangerousGoodsAttributeType }
     * 
     */
    public DangerousGoodsAttributeType createDangerousGoodsAttributeType() {
        return new DangerousGoodsAttributeType();
    }

    /**
     * Create an instance of {@link LogisticUnitsType }
     * 
     */
    public LogisticUnitsType createLogisticUnitsType() {
        return new LogisticUnitsType();
    }

    /**
     * Create an instance of {@link CollaborativeTradeItemType }
     * 
     */
    public CollaborativeTradeItemType createCollaborativeTradeItemType() {
        return new CollaborativeTradeItemType();
    }

    /**
     * Create an instance of {@link LogisticServiceRequirementCodeType }
     * 
     */
    public LogisticServiceRequirementCodeType createLogisticServiceRequirementCodeType() {
        return new LogisticServiceRequirementCodeType();
    }

    /**
     * Create an instance of {@link OrderLogisticalInformationType }
     * 
     */
    public OrderLogisticalInformationType createOrderLogisticalInformationType() {
        return new OrderLogisticalInformationType();
    }

    /**
     * Create an instance of {@link FinancialAdjustmentReasonCodeType }
     * 
     */
    public FinancialAdjustmentReasonCodeType createFinancialAdjustmentReasonCodeType() {
        return new FinancialAdjustmentReasonCodeType();
    }

    /**
     * Create an instance of {@link CargoTypeCodeType }
     * 
     */
    public CargoTypeCodeType createCargoTypeCodeType() {
        return new CargoTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportServiceConditionTypeCodeType }
     * 
     */
    public TransportServiceConditionTypeCodeType createTransportServiceConditionTypeCodeType() {
        return new TransportServiceConditionTypeCodeType();
    }

    /**
     * Create an instance of {@link WarehouseABCClassificationCodeType }
     * 
     */
    public WarehouseABCClassificationCodeType createWarehouseABCClassificationCodeType() {
        return new WarehouseABCClassificationCodeType();
    }

    /**
     * Create an instance of {@link SettlementTypeCodeType }
     * 
     */
    public SettlementTypeCodeType createSettlementTypeCodeType() {
        return new SettlementTypeCodeType();
    }

    /**
     * Create an instance of {@link EcomDocumentType }
     * 
     */
    public EcomDocumentType createEcomDocumentType() {
        return new EcomDocumentType();
    }

    /**
     * Create an instance of {@link LogisticServiceReferenceTypeCodeType }
     * 
     */
    public LogisticServiceReferenceTypeCodeType createLogisticServiceReferenceTypeCodeType() {
        return new LogisticServiceReferenceTypeCodeType();
    }

    /**
     * Create an instance of {@link DangerousGoodsInformationType }
     * 
     */
    public DangerousGoodsInformationType createDangerousGoodsInformationType() {
        return new DangerousGoodsInformationType();
    }

    /**
     * Create an instance of {@link PackageTotalType }
     * 
     */
    public PackageTotalType createPackageTotalType() {
        return new PackageTotalType();
    }

    /**
     * Create an instance of {@link ItemScopeTypeCodeType }
     * 
     */
    public ItemScopeTypeCodeType createItemScopeTypeCodeType() {
        return new ItemScopeTypeCodeType();
    }

    /**
     * Create an instance of {@link LegalRegistrationType }
     * 
     */
    public LegalRegistrationType createLegalRegistrationType() {
        return new LegalRegistrationType();
    }

    /**
     * Create an instance of {@link TransportStatusType }
     * 
     */
    public TransportStatusType createTransportStatusType() {
        return new TransportStatusType();
    }

    /**
     * Create an instance of {@link EcomAttributeValuePairListType }
     * 
     */
    public EcomAttributeValuePairListType createEcomAttributeValuePairListType() {
        return new EcomAttributeValuePairListType();
    }

    /**
     * Create an instance of {@link ConsignmentReferenceType }
     * 
     */
    public ConsignmentReferenceType createConsignmentReferenceType() {
        return new ConsignmentReferenceType();
    }

    /**
     * Create an instance of {@link PaymentFormatCodeType }
     * 
     */
    public PaymentFormatCodeType createPaymentFormatCodeType() {
        return new PaymentFormatCodeType();
    }

    /**
     * Create an instance of {@link TransportMeansTypeCodeType }
     * 
     */
    public TransportMeansTypeCodeType createTransportMeansTypeCodeType() {
        return new TransportMeansTypeCodeType();
    }

    /**
     * Create an instance of {@link LogisticServiceType }
     * 
     */
    public LogisticServiceType createLogisticServiceType() {
        return new LogisticServiceType();
    }

    /**
     * Create an instance of {@link OutOfStockMeasurementTypeCodeType }
     * 
     */
    public OutOfStockMeasurementTypeCodeType createOutOfStockMeasurementTypeCodeType() {
        return new OutOfStockMeasurementTypeCodeType();
    }

    /**
     * Create an instance of {@link CarrierTrackAndTraceInformationType }
     * 
     */
    public CarrierTrackAndTraceInformationType createCarrierTrackAndTraceInformationType() {
        return new CarrierTrackAndTraceInformationType();
    }

    /**
     * Create an instance of {@link TransportInstructionStatusReasonCodeType }
     * 
     */
    public TransportInstructionStatusReasonCodeType createTransportInstructionStatusReasonCodeType() {
        return new TransportInstructionStatusReasonCodeType();
    }

    /**
     * Create an instance of {@link SourceReferenceType }
     * 
     */
    public SourceReferenceType createSourceReferenceType() {
        return new SourceReferenceType();
    }

    /**
     * Create an instance of {@link LogisticEventTypeCodeType }
     * 
     */
    public LogisticEventTypeCodeType createLogisticEventTypeCodeType() {
        return new LogisticEventTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportSealType }
     * 
     */
    public TransportSealType createTransportSealType() {
        return new TransportSealType();
    }

    /**
     * Create an instance of {@link PlanBucketSizeCodeType }
     * 
     */
    public PlanBucketSizeCodeType createPlanBucketSizeCodeType() {
        return new PlanBucketSizeCodeType();
    }

    /**
     * Create an instance of {@link InventoryMeasurementBasisTypeCodeType }
     * 
     */
    public InventoryMeasurementBasisTypeCodeType createInventoryMeasurementBasisTypeCodeType() {
        return new InventoryMeasurementBasisTypeCodeType();
    }

    /**
     * Create an instance of {@link DespatchInformationType }
     * 
     */
    public DespatchInformationType createDespatchInformationType() {
        return new DespatchInformationType();
    }

    /**
     * Create an instance of {@link LegalRegistrationCodeType }
     * 
     */
    public LegalRegistrationCodeType createLegalRegistrationCodeType() {
        return new LegalRegistrationCodeType();
    }

    /**
     * Create an instance of {@link LogisticEventType }
     * 
     */
    public LogisticEventType createLogisticEventType() {
        return new LogisticEventType();
    }

    /**
     * Create an instance of {@link AdministrativeUnitTypeCodeType }
     * 
     */
    public AdministrativeUnitTypeCodeType createAdministrativeUnitTypeCodeType() {
        return new AdministrativeUnitTypeCodeType();
    }

    /**
     * Create an instance of {@link LineItemActionCodeType }
     * 
     */
    public LineItemActionCodeType createLineItemActionCodeType() {
        return new LineItemActionCodeType();
    }

    /**
     * Create an instance of {@link InventorySubLocationTypeCodeType }
     * 
     */
    public InventorySubLocationTypeCodeType createInventorySubLocationTypeCodeType() {
        return new InventorySubLocationTypeCodeType();
    }

    /**
     * Create an instance of {@link LowerLevelTradeItemType }
     * 
     */
    public LowerLevelTradeItemType createLowerLevelTradeItemType() {
        return new LowerLevelTradeItemType();
    }

    /**
     * Create an instance of {@link InventoryDutyFeeTaxStatusType }
     * 
     */
    public InventoryDutyFeeTaxStatusType createInventoryDutyFeeTaxStatusType() {
        return new InventoryDutyFeeTaxStatusType();
    }

    /**
     * Create an instance of {@link DataCarrierTypeCodeType }
     * 
     */
    public DataCarrierTypeCodeType createDataCarrierTypeCodeType() {
        return new DataCarrierTypeCodeType();
    }

    /**
     * Create an instance of {@link CustomsWarehouseStatusCodeType }
     * 
     */
    public CustomsWarehouseStatusCodeType createCustomsWarehouseStatusCodeType() {
        return new CustomsWarehouseStatusCodeType();
    }

    /**
     * Create an instance of {@link LocationScopeTypeCodeType }
     * 
     */
    public LocationScopeTypeCodeType createLocationScopeTypeCodeType() {
        return new LocationScopeTypeCodeType();
    }

    /**
     * Create an instance of {@link AdministrativeUnitType }
     * 
     */
    public AdministrativeUnitType createAdministrativeUnitType() {
        return new AdministrativeUnitType();
    }

    /**
     * Create an instance of {@link OrderLogisticalDateInformationType }
     * 
     */
    public OrderLogisticalDateInformationType createOrderLogisticalDateInformationType() {
        return new OrderLogisticalDateInformationType();
    }

    /**
     * Create an instance of {@link AllowanceChargeType }
     * 
     */
    public AllowanceChargeType createAllowanceChargeType() {
        return new AllowanceChargeType();
    }

    /**
     * Create an instance of {@link PassengerInformationType }
     * 
     */
    public PassengerInformationType createPassengerInformationType() {
        return new PassengerInformationType();
    }

    /**
     * Create an instance of {@link PeriodicityTypeCodeType }
     * 
     */
    public PeriodicityTypeCodeType createPeriodicityTypeCodeType() {
        return new PeriodicityTypeCodeType();
    }

    /**
     * Create an instance of {@link InventoryStatusCodeType }
     * 
     */
    public InventoryStatusCodeType createInventoryStatusCodeType() {
        return new InventoryStatusCodeType();
    }

    /**
     * Create an instance of {@link PackagingConditionCodeType }
     * 
     */
    public PackagingConditionCodeType createPackagingConditionCodeType() {
        return new PackagingConditionCodeType();
    }

    /**
     * Create an instance of {@link ServiceLevelBasisTypeCodeType }
     * 
     */
    public ServiceLevelBasisTypeCodeType createServiceLevelBasisTypeCodeType() {
        return new ServiceLevelBasisTypeCodeType();
    }

    /**
     * Create an instance of {@link GoodsReceiptReportingCodeType }
     * 
     */
    public GoodsReceiptReportingCodeType createGoodsReceiptReportingCodeType() {
        return new GoodsReceiptReportingCodeType();
    }

    /**
     * Create an instance of {@link TransactionalReferenceTypeCodeType }
     * 
     */
    public TransactionalReferenceTypeCodeType createTransactionalReferenceTypeCodeType() {
        return new TransactionalReferenceTypeCodeType();
    }

    /**
     * Create an instance of {@link StockRequirementTypeCodeType }
     * 
     */
    public StockRequirementTypeCodeType createStockRequirementTypeCodeType() {
        return new StockRequirementTypeCodeType();
    }

    /**
     * Create an instance of {@link InstallmentDueType }
     * 
     */
    public InstallmentDueType createInstallmentDueType() {
        return new InstallmentDueType();
    }

    /**
     * Create an instance of {@link TradeItemUnitDescriptorCodeType }
     * 
     */
    public TradeItemUnitDescriptorCodeType createTradeItemUnitDescriptorCodeType() {
        return new TradeItemUnitDescriptorCodeType();
    }

    /**
     * Create an instance of {@link PartyReferenceType }
     * 
     */
    public PartyReferenceType createPartyReferenceType() {
        return new PartyReferenceType();
    }

    /**
     * Create an instance of {@link PrintingInstructionCodeType }
     * 
     */
    public PrintingInstructionCodeType createPrintingInstructionCodeType() {
        return new PrintingInstructionCodeType();
    }

    /**
     * Create an instance of {@link EffectiveDateTypeCodeType }
     * 
     */
    public EffectiveDateTypeCodeType createEffectiveDateTypeCodeType() {
        return new EffectiveDateTypeCodeType();
    }

    /**
     * Create an instance of {@link SealConditionCodeType }
     * 
     */
    public SealConditionCodeType createSealConditionCodeType() {
        return new SealConditionCodeType();
    }

    /**
     * Create an instance of {@link ResponseStatusCodeType }
     * 
     */
    public ResponseStatusCodeType createResponseStatusCodeType() {
        return new ResponseStatusCodeType();
    }

    /**
     * Create an instance of {@link PackageTypeCodeType }
     * 
     */
    public PackageTypeCodeType createPackageTypeCodeType() {
        return new PackageTypeCodeType();
    }

    /**
     * Create an instance of {@link IdentityDocumentTypeCodeType }
     * 
     */
    public IdentityDocumentTypeCodeType createIdentityDocumentTypeCodeType() {
        return new IdentityDocumentTypeCodeType();
    }

    /**
     * Create an instance of {@link SealTypeCodeType }
     * 
     */
    public SealTypeCodeType createSealTypeCodeType() {
        return new SealTypeCodeType();
    }

    /**
     * Create an instance of {@link DeliveryTypeCodeType }
     * 
     */
    public DeliveryTypeCodeType createDeliveryTypeCodeType() {
        return new DeliveryTypeCodeType();
    }

    /**
     * Create an instance of {@link InventorySubLocationFunctionCodeType }
     * 
     */
    public InventorySubLocationFunctionCodeType createInventorySubLocationFunctionCodeType() {
        return new InventorySubLocationFunctionCodeType();
    }

    /**
     * Create an instance of {@link TransportReferenceTypeCodeType }
     * 
     */
    public TransportReferenceTypeCodeType createTransportReferenceTypeCodeType() {
        return new TransportReferenceTypeCodeType();
    }

    /**
     * Create an instance of {@link DeliverDateInformationType }
     * 
     */
    public DeliverDateInformationType createDeliverDateInformationType() {
        return new DeliverDateInformationType();
    }

    /**
     * Create an instance of {@link QuantitySpecificationType }
     * 
     */
    public QuantitySpecificationType createQuantitySpecificationType() {
        return new QuantitySpecificationType();
    }

    /**
     * Create an instance of {@link PerformanceMeasureTypeCodeType }
     * 
     */
    public PerformanceMeasureTypeCodeType createPerformanceMeasureTypeCodeType() {
        return new PerformanceMeasureTypeCodeType();
    }

    /**
     * Create an instance of {@link ObservationTypeCodeType }
     * 
     */
    public ObservationTypeCodeType createObservationTypeCodeType() {
        return new ObservationTypeCodeType();
    }

    /**
     * Create an instance of {@link TransactionalPartyType }
     * 
     */
    public TransactionalPartyType createTransactionalPartyType() {
        return new TransactionalPartyType();
    }

    /**
     * Create an instance of {@link PaymentTermsType }
     * 
     */
    public PaymentTermsType createPaymentTermsType() {
        return new PaymentTermsType();
    }

    /**
     * Create an instance of {@link InventorySubLocationType }
     * 
     */
    public InventorySubLocationType createInventorySubLocationType() {
        return new InventorySubLocationType();
    }

    /**
     * Create an instance of {@link TransportTrackingLogEventType }
     * 
     */
    public TransportTrackingLogEventType createTransportTrackingLogEventType() {
        return new TransportTrackingLogEventType();
    }

    /**
     * Create an instance of {@link MaterialTypeCodeType }
     * 
     */
    public MaterialTypeCodeType createMaterialTypeCodeType() {
        return new MaterialTypeCodeType();
    }

    /**
     * Create an instance of {@link PaymentTermsDiscountType }
     * 
     */
    public PaymentTermsDiscountType createPaymentTermsDiscountType() {
        return new PaymentTermsDiscountType();
    }

    /**
     * Create an instance of {@link ForecastPurposeCodeType }
     * 
     */
    public ForecastPurposeCodeType createForecastPurposeCodeType() {
        return new ForecastPurposeCodeType();
    }

    /**
     * Create an instance of {@link InventoryMovementTypeCodeType }
     * 
     */
    public InventoryMovementTypeCodeType createInventoryMovementTypeCodeType() {
        return new InventoryMovementTypeCodeType();
    }

    /**
     * Create an instance of {@link TransactionalReferenceType }
     * 
     */
    public TransactionalReferenceType createTransactionalReferenceType() {
        return new TransactionalReferenceType();
    }

    /**
     * Create an instance of {@link DangerousGoodsAttributeTypeCodeType }
     * 
     */
    public DangerousGoodsAttributeTypeCodeType createDangerousGoodsAttributeTypeCodeType() {
        return new DangerousGoodsAttributeTypeCodeType();
    }

    /**
     * Create an instance of {@link DemandEstimationTypeCodeType }
     * 
     */
    public DemandEstimationTypeCodeType createDemandEstimationTypeCodeType() {
        return new DemandEstimationTypeCodeType();
    }

    /**
     * Create an instance of {@link DangerousGoodsRegulationCodeType }
     * 
     */
    public DangerousGoodsRegulationCodeType createDangerousGoodsRegulationCodeType() {
        return new DangerousGoodsRegulationCodeType();
    }

    /**
     * Create an instance of {@link LogisticUnitType }
     * 
     */
    public LogisticUnitType createLogisticUnitType() {
        return new LogisticUnitType();
    }

    /**
     * Create an instance of {@link UnitMeasurementType }
     * 
     */
    public UnitMeasurementType createUnitMeasurementType() {
        return new UnitMeasurementType();
    }

    /**
     * Create an instance of {@link TransportStatusReasonCodeType }
     * 
     */
    public TransportStatusReasonCodeType createTransportStatusReasonCodeType() {
        return new TransportStatusReasonCodeType();
    }

    /**
     * Create an instance of {@link ShipmentReferenceType }
     * 
     */
    public ShipmentReferenceType createShipmentReferenceType() {
        return new ShipmentReferenceType();
    }

    /**
     * Create an instance of {@link DeliveryTimeMeasurementBasisTypeCodeType }
     * 
     */
    public DeliveryTimeMeasurementBasisTypeCodeType createDeliveryTimeMeasurementBasisTypeCodeType() {
        return new DeliveryTimeMeasurementBasisTypeCodeType();
    }

    /**
     * Create an instance of {@link OperatingHoursType }
     * 
     */
    public OperatingHoursType createOperatingHoursType() {
        return new OperatingHoursType();
    }

    /**
     * Create an instance of {@link PurchaseConditionsCommitmentTypeCodeType }
     * 
     */
    public PurchaseConditionsCommitmentTypeCodeType createPurchaseConditionsCommitmentTypeCodeType() {
        return new PurchaseConditionsCommitmentTypeCodeType();
    }

    /**
     * Create an instance of {@link ChildPackageLevelType }
     * 
     */
    public ChildPackageLevelType createChildPackageLevelType() {
        return new ChildPackageLevelType();
    }

    /**
     * Create an instance of {@link DeliveryTermsType }
     * 
     */
    public DeliveryTermsType createDeliveryTermsType() {
        return new DeliveryTermsType();
    }

    /**
     * Create an instance of {@link TransportMeansType }
     * 
     */
    public TransportMeansType createTransportMeansType() {
        return new TransportMeansType();
    }

    /**
     * Create an instance of {@link InventoryStatusQuantitySpecificationType }
     * 
     */
    public InventoryStatusQuantitySpecificationType createInventoryStatusQuantitySpecificationType() {
        return new InventoryStatusQuantitySpecificationType();
    }

    /**
     * Create an instance of {@link SalesMeasurementTypeCodeType }
     * 
     */
    public SalesMeasurementTypeCodeType createSalesMeasurementTypeCodeType() {
        return new SalesMeasurementTypeCodeType();
    }

    /**
     * Create an instance of {@link LogisticServiceReferenceType }
     * 
     */
    public LogisticServiceReferenceType createLogisticServiceReferenceType() {
        return new LogisticServiceReferenceType();
    }

    /**
     * Create an instance of {@link FinancialInstitutionInformationType }
     * 
     */
    public FinancialInstitutionInformationType createFinancialInstitutionInformationType() {
        return new FinancialInstitutionInformationType();
    }

    /**
     * Create an instance of {@link MeasurementTypeCodeType }
     * 
     */
    public MeasurementTypeCodeType createMeasurementTypeCodeType() {
        return new MeasurementTypeCodeType();
    }

    /**
     * Create an instance of {@link ReturnablePackagingType }
     * 
     */
    public ReturnablePackagingType createReturnablePackagingType() {
        return new ReturnablePackagingType();
    }

    /**
     * Create an instance of {@link CreditReasonCodeType }
     * 
     */
    public CreditReasonCodeType createCreditReasonCodeType() {
        return new CreditReasonCodeType();
    }

    /**
     * Create an instance of {@link TransportTrackingSensorObservationType }
     * 
     */
    public TransportTrackingSensorObservationType createTransportTrackingSensorObservationType() {
        return new TransportTrackingSensorObservationType();
    }

    /**
     * Create an instance of {@link PackageLevelCodeType }
     * 
     */
    public PackageLevelCodeType createPackageLevelCodeType() {
        return new PackageLevelCodeType();
    }

    /**
     * Create an instance of {@link DutyFeeTaxRegistrationType }
     * 
     */
    public DutyFeeTaxRegistrationType createDutyFeeTaxRegistrationType() {
        return new DutyFeeTaxRegistrationType();
    }

    /**
     * Create an instance of {@link DeliverDateTypeCodeType }
     * 
     */
    public DeliverDateTypeCodeType createDeliverDateTypeCodeType() {
        return new DeliverDateTypeCodeType();
    }

    /**
     * Create an instance of {@link UNLocationCodeType }
     * 
     */
    public UNLocationCodeType createUNLocationCodeType() {
        return new UNLocationCodeType();
    }

    /**
     * Create an instance of {@link VarianceReasonCodeType }
     * 
     */
    public VarianceReasonCodeType createVarianceReasonCodeType() {
        return new VarianceReasonCodeType();
    }

    /**
     * Create an instance of {@link TransactionalPartyInRoleType }
     * 
     */
    public TransactionalPartyInRoleType createTransactionalPartyInRoleType() {
        return new TransactionalPartyInRoleType();
    }

    /**
     * Create an instance of {@link LeviedDutyFeeTaxType }
     * 
     */
    public LeviedDutyFeeTaxType createLeviedDutyFeeTaxType() {
        return new LeviedDutyFeeTaxType();
    }

    /**
     * Create an instance of {@link MarginSchemeCodeType }
     * 
     */
    public MarginSchemeCodeType createMarginSchemeCodeType() {
        return new MarginSchemeCodeType();
    }

    /**
     * Create an instance of {@link QuantitySpecificationTypeCodeType }
     * 
     */
    public QuantitySpecificationTypeCodeType createQuantitySpecificationTypeCodeType() {
        return new QuantitySpecificationTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportPartyRoleCodeType }
     * 
     */
    public TransportPartyRoleCodeType createTransportPartyRoleCodeType() {
        return new TransportPartyRoleCodeType();
    }

    /**
     * Create an instance of {@link SpecialOperatingHoursType }
     * 
     */
    public SpecialOperatingHoursType createSpecialOperatingHoursType() {
        return new SpecialOperatingHoursType();
    }

    /**
     * Create an instance of {@link LogisticUnitMeasurementType }
     * 
     */
    public LogisticUnitMeasurementType createLogisticUnitMeasurementType() {
        return new LogisticUnitMeasurementType();
    }

    /**
     * Create an instance of {@link TransportReferenceType }
     * 
     */
    public TransportReferenceType createTransportReferenceType() {
        return new TransportReferenceType();
    }

    /**
     * Create an instance of {@link PaymentTermsEventCodeType }
     * 
     */
    public PaymentTermsEventCodeType createPaymentTermsEventCodeType() {
        return new PaymentTermsEventCodeType();
    }

    /**
     * Create an instance of {@link HandlingInstructionType }
     * 
     */
    public HandlingInstructionType createHandlingInstructionType() {
        return new HandlingInstructionType();
    }

    /**
     * Create an instance of {@link TransportPaymentMethodCodeType }
     * 
     */
    public TransportPaymentMethodCodeType createTransportPaymentMethodCodeType() {
        return new TransportPaymentMethodCodeType();
    }

    /**
     * Create an instance of {@link SynchronisationCalculationTypeCodeType }
     * 
     */
    public SynchronisationCalculationTypeCodeType createSynchronisationCalculationTypeCodeType() {
        return new SynchronisationCalculationTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportEquipmentType }
     * 
     */
    public TransportEquipmentType createTransportEquipmentType() {
        return new TransportEquipmentType();
    }

    /**
     * Create an instance of {@link ReceivingConditionCodeType }
     * 
     */
    public ReceivingConditionCodeType createReceivingConditionCodeType() {
        return new ReceivingConditionCodeType();
    }

    /**
     * Create an instance of {@link CarrierPickUpDropOffDetailsType }
     * 
     */
    public CarrierPickUpDropOffDetailsType createCarrierPickUpDropOffDetailsType() {
        return new CarrierPickUpDropOffDetailsType();
    }

    /**
     * Create an instance of {@link LogisticLocationType }
     * 
     */
    public LogisticLocationType createLogisticLocationType() {
        return new LogisticLocationType();
    }

    /**
     * Create an instance of {@link SettlementHandlingTypeCodeType }
     * 
     */
    public SettlementHandlingTypeCodeType createSettlementHandlingTypeCodeType() {
        return new SettlementHandlingTypeCodeType();
    }

    /**
     * Create an instance of {@link PassengerCategoryCodeType }
     * 
     */
    public PassengerCategoryCodeType createPassengerCategoryCodeType() {
        return new PassengerCategoryCodeType();
    }

    /**
     * Create an instance of {@link InvoiceDocumentReferenceType }
     * 
     */
    public InvoiceDocumentReferenceType createInvoiceDocumentReferenceType() {
        return new InvoiceDocumentReferenceType();
    }

    /**
     * Create an instance of {@link TransportServiceLevelCodeType }
     * 
     */
    public TransportServiceLevelCodeType createTransportServiceLevelCodeType() {
        return new TransportServiceLevelCodeType();
    }

    /**
     * Create an instance of {@link TransportCargoCharacteristicsType }
     * 
     */
    public TransportCargoCharacteristicsType createTransportCargoCharacteristicsType() {
        return new TransportCargoCharacteristicsType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link DutyFeeTaxTypeCodeType }
     * 
     */
    public DutyFeeTaxTypeCodeType createDutyFeeTaxTypeCodeType() {
        return new DutyFeeTaxTypeCodeType();
    }

    /**
     * Create an instance of {@link PackagingMarkingTypeCodeType }
     * 
     */
    public PackagingMarkingTypeCodeType createPackagingMarkingTypeCodeType() {
        return new PackagingMarkingTypeCodeType();
    }

    /**
     * Create an instance of {@link PaymentMethodType }
     * 
     */
    public PaymentMethodType createPaymentMethodType() {
        return new PaymentMethodType();
    }

    /**
     * Create an instance of {@link PlanCommitmentLevelCodeType }
     * 
     */
    public PlanCommitmentLevelCodeType createPlanCommitmentLevelCodeType() {
        return new PlanCommitmentLevelCodeType();
    }

    /**
     * Create an instance of {@link ErrorOrWarningCodeType }
     * 
     */
    public ErrorOrWarningCodeType createErrorOrWarningCodeType() {
        return new ErrorOrWarningCodeType();
    }

    /**
     * Create an instance of {@link AppointmentTimeMeasurementBasisTypeCodeType }
     * 
     */
    public AppointmentTimeMeasurementBasisTypeCodeType createAppointmentTimeMeasurementBasisTypeCodeType() {
        return new AppointmentTimeMeasurementBasisTypeCodeType();
    }

    /**
     * Create an instance of {@link StructureTypeCodeType }
     * 
     */
    public StructureTypeCodeType createStructureTypeCodeType() {
        return new StructureTypeCodeType();
    }

    /**
     * Create an instance of {@link TransactionalTradeItemType }
     * 
     */
    public TransactionalTradeItemType createTransactionalTradeItemType() {
        return new TransactionalTradeItemType();
    }

    /**
     * Create an instance of {@link ShipmentTransportationInformationType }
     * 
     */
    public ShipmentTransportationInformationType createShipmentTransportationInformationType() {
        return new ShipmentTransportationInformationType();
    }

    /**
     * Create an instance of {@link HandlingInstructionCodeType }
     * 
     */
    public HandlingInstructionCodeType createHandlingInstructionCodeType() {
        return new HandlingInstructionCodeType();
    }

    /**
     * Create an instance of {@link LocationScopeParameterTypeCodeType }
     * 
     */
    public LocationScopeParameterTypeCodeType createLocationScopeParameterTypeCodeType() {
        return new LocationScopeParameterTypeCodeType();
    }

    /**
     * Create an instance of {@link OrganisationType }
     * 
     */
    public OrganisationType createOrganisationType() {
        return new OrganisationType();
    }

    /**
     * Create an instance of {@link EcomStringAttributeValuePairListType }
     * 
     */
    public EcomStringAttributeValuePairListType createEcomStringAttributeValuePairListType() {
        return new EcomStringAttributeValuePairListType();
    }

    /**
     * Create an instance of {@link OrderInstructionCodeType }
     * 
     */
    public OrderInstructionCodeType createOrderInstructionCodeType() {
        return new OrderInstructionCodeType();
    }

    /**
     * Create an instance of {@link SpecialServiceTypeCodeType }
     * 
     */
    public SpecialServiceTypeCodeType createSpecialServiceTypeCodeType() {
        return new SpecialServiceTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportModeCodeType }
     * 
     */
    public TransportModeCodeType createTransportModeCodeType() {
        return new TransportModeCodeType();
    }

    /**
     * Create an instance of {@link SymbolComponentCodeType }
     * 
     */
    public SymbolComponentCodeType createSymbolComponentCodeType() {
        return new SymbolComponentCodeType();
    }

    /**
     * Create an instance of {@link ServiceLevelMeasurementBasisTypeCodeType }
     * 
     */
    public ServiceLevelMeasurementBasisTypeCodeType createServiceLevelMeasurementBasisTypeCodeType() {
        return new ServiceLevelMeasurementBasisTypeCodeType();
    }

    /**
     * Create an instance of {@link TransactionalItemDataType }
     * 
     */
    public TransactionalItemDataType createTransactionalItemDataType() {
        return new TransactionalItemDataType();
    }

    /**
     * Create an instance of {@link TransportTrackingObservationType }
     * 
     */
    public TransportTrackingObservationType createTransportTrackingObservationType() {
        return new TransportTrackingObservationType();
    }

    /**
     * Create an instance of {@link LocationInformationType }
     * 
     */
    public LocationInformationType createLocationInformationType() {
        return new LocationInformationType();
    }

    /**
     * Create an instance of {@link TransportServiceCategoryCodeType }
     * 
     */
    public TransportServiceCategoryCodeType createTransportServiceCategoryCodeType() {
        return new TransportServiceCategoryCodeType();
    }

    /**
     * Create an instance of {@link OrderTypeCodeType }
     * 
     */
    public OrderTypeCodeType createOrderTypeCodeType() {
        return new OrderTypeCodeType();
    }

    /**
     * Create an instance of {@link TimePeriodScopeTypeCodeType }
     * 
     */
    public TimePeriodScopeTypeCodeType createTimePeriodScopeTypeCodeType() {
        return new TimePeriodScopeTypeCodeType();
    }

    /**
     * Create an instance of {@link ForecastTypeCodeType }
     * 
     */
    public ForecastTypeCodeType createForecastTypeCodeType() {
        return new ForecastTypeCodeType();
    }

    /**
     * Create an instance of {@link QualityControlCodeType }
     * 
     */
    public QualityControlCodeType createQualityControlCodeType() {
        return new QualityControlCodeType();
    }

    /**
     * Create an instance of {@link InvoiceTypeCodeType }
     * 
     */
    public InvoiceTypeCodeType createInvoiceTypeCodeType() {
        return new InvoiceTypeCodeType();
    }

    /**
     * Create an instance of {@link HarmonizedSystemCodeType }
     * 
     */
    public HarmonizedSystemCodeType createHarmonizedSystemCodeType() {
        return new HarmonizedSystemCodeType();
    }

    /**
     * Create an instance of {@link RemainingQuantityStatusCodeType }
     * 
     */
    public RemainingQuantityStatusCodeType createRemainingQuantityStatusCodeType() {
        return new RemainingQuantityStatusCodeType();
    }

    /**
     * Create an instance of {@link DangerousGoodsRegulationInformationType }
     * 
     */
    public DangerousGoodsRegulationInformationType createDangerousGoodsRegulationInformationType() {
        return new DangerousGoodsRegulationInformationType();
    }

    /**
     * Create an instance of {@link TransportStatusConditionCodeType }
     * 
     */
    public TransportStatusConditionCodeType createTransportStatusConditionCodeType() {
        return new TransportStatusConditionCodeType();
    }

    /**
     * Create an instance of {@link IdentityDocumentType }
     * 
     */
    public IdentityDocumentType createIdentityDocumentType() {
        return new IdentityDocumentType();
    }

    /**
     * Create an instance of {@link PackagingMarkingType }
     * 
     */
    public PackagingMarkingType createPackagingMarkingType() {
        return new PackagingMarkingType();
    }

    /**
     * Create an instance of {@link ItemTypeCodeType }
     * 
     */
    public ItemTypeCodeType createItemTypeCodeType() {
        return new ItemTypeCodeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "ScopeInformation")
    public JAXBElement<Object> createScopeInformation(Object value) {
        return new JAXBElement<Object>(_ScopeInformation_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorrelationInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "CorrelationInformation", substitutionHeadNamespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", substitutionHeadName = "ScopeInformation")
    public JAXBElement<CorrelationInformation> createCorrelationInformation(CorrelationInformation value) {
        return new JAXBElement<CorrelationInformation>(_CorrelationInformation_QNAME, CorrelationInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardBusinessDocumentHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "StandardBusinessDocumentHeader")
    public JAXBElement<StandardBusinessDocumentHeader> createStandardBusinessDocumentHeader(StandardBusinessDocumentHeader value) {
        return new JAXBElement<StandardBusinessDocumentHeader>(_StandardBusinessDocumentHeader_QNAME, StandardBusinessDocumentHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "BusinessService", substitutionHeadNamespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", substitutionHeadName = "ScopeInformation")
    public JAXBElement<BusinessService> createBusinessService(BusinessService value) {
        return new JAXBElement<BusinessService>(_BusinessService_QNAME, BusinessService.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardBusinessDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "StandardBusinessDocument")
    public JAXBElement<StandardBusinessDocument> createStandardBusinessDocument(StandardBusinessDocument value) {
        return new JAXBElement<StandardBusinessDocument>(_StandardBusinessDocument_QNAME, StandardBusinessDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArtworkContentMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:gs1:ecom:artwork_content:xsd:3", name = "artworkContentMessage")
    public JAXBElement<ArtworkContentMessageType> createArtworkContentMessage(ArtworkContentMessageType value) {
        return new JAXBElement<ArtworkContentMessageType>(_ArtworkContentMessage_QNAME, ArtworkContentMessageType.class, null, value);
    }

}
