//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderLogisticalInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderLogisticalInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shipFrom" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="shipTo" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="inventoryLocation" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="ultimateConsignee" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="orderLogisticalDateInformation" type="{urn:gs1:ecom:ecom_common:xsd:3}OrderLogisticalDateInformationType" minOccurs="0"/>
 *         &lt;element name="shipmentTransportationInformation" type="{urn:gs1:ecom:ecom_common:xsd:3}ShipmentTransportationInformationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderLogisticalInformationType", propOrder = {
    "shipFrom",
    "shipTo",
    "inventoryLocation",
    "ultimateConsignee",
    "orderLogisticalDateInformation",
    "shipmentTransportationInformation"
})
public class OrderLogisticalInformationType {

    protected TransactionalPartyType shipFrom;
    protected TransactionalPartyType shipTo;
    protected TransactionalPartyType inventoryLocation;
    protected TransactionalPartyType ultimateConsignee;
    protected OrderLogisticalDateInformationType orderLogisticalDateInformation;
    protected ShipmentTransportationInformationType shipmentTransportationInformation;

    /**
     * Gets the value of the shipFrom property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getShipFrom() {
        return shipFrom;
    }

    /**
     * Sets the value of the shipFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setShipFrom(TransactionalPartyType value) {
        this.shipFrom = value;
    }

    /**
     * Gets the value of the shipTo property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getShipTo() {
        return shipTo;
    }

    /**
     * Sets the value of the shipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setShipTo(TransactionalPartyType value) {
        this.shipTo = value;
    }

    /**
     * Gets the value of the inventoryLocation property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getInventoryLocation() {
        return inventoryLocation;
    }

    /**
     * Sets the value of the inventoryLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setInventoryLocation(TransactionalPartyType value) {
        this.inventoryLocation = value;
    }

    /**
     * Gets the value of the ultimateConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getUltimateConsignee() {
        return ultimateConsignee;
    }

    /**
     * Sets the value of the ultimateConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setUltimateConsignee(TransactionalPartyType value) {
        this.ultimateConsignee = value;
    }

    /**
     * Gets the value of the orderLogisticalDateInformation property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLogisticalDateInformationType }
     *     
     */
    public OrderLogisticalDateInformationType getOrderLogisticalDateInformation() {
        return orderLogisticalDateInformation;
    }

    /**
     * Sets the value of the orderLogisticalDateInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLogisticalDateInformationType }
     *     
     */
    public void setOrderLogisticalDateInformation(OrderLogisticalDateInformationType value) {
        this.orderLogisticalDateInformation = value;
    }

    /**
     * Gets the value of the shipmentTransportationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentTransportationInformationType }
     *     
     */
    public ShipmentTransportationInformationType getShipmentTransportationInformation() {
        return shipmentTransportationInformation;
    }

    /**
     * Sets the value of the shipmentTransportationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentTransportationInformationType }
     *     
     */
    public void setShipmentTransportationInformation(ShipmentTransportationInformationType value) {
        this.shipmentTransportationInformation = value;
    }

}
