//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PackagingMarkingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackagingMarkingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="markingTypeCode" type="{urn:gs1:ecom:ecom_common:xsd:3}PackagingMarkingTypeCodeType"/>
 *         &lt;element name="markingContentDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="markingContentText" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackagingMarkingType", propOrder = {
    "markingTypeCode",
    "markingContentDateTime",
    "markingContentText"
})
public class PackagingMarkingType {

    @XmlElement(required = true)
    protected PackagingMarkingTypeCodeType markingTypeCode;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar markingContentDateTime;
    protected String markingContentText;

    /**
     * Gets the value of the markingTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link PackagingMarkingTypeCodeType }
     *     
     */
    public PackagingMarkingTypeCodeType getMarkingTypeCode() {
        return markingTypeCode;
    }

    /**
     * Sets the value of the markingTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackagingMarkingTypeCodeType }
     *     
     */
    public void setMarkingTypeCode(PackagingMarkingTypeCodeType value) {
        this.markingTypeCode = value;
    }

    /**
     * Gets the value of the markingContentDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMarkingContentDateTime() {
        return markingContentDateTime;
    }

    /**
     * Sets the value of the markingContentDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMarkingContentDateTime(XMLGregorianCalendar value) {
        this.markingContentDateTime = value;
    }

    /**
     * Gets the value of the markingContentText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkingContentText() {
        return markingContentText;
    }

    /**
     * Sets the value of the markingContentText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkingContentText(String value) {
        this.markingContentText = value;
    }

}
