//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PassengerInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PassengerInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numberOfPassengers" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="passengerCategoryCode" type="{urn:gs1:ecom:ecom_common:xsd:3}PassengerCategoryCodeType" minOccurs="0"/>
 *         &lt;element name="passengerTariffGroup" type="{urn:gs1:shared:shared_common:xsd:3}Description80Type" minOccurs="0"/>
 *         &lt;element name="person" type="{urn:gs1:ecom:ecom_common:xsd:3}PersonType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PassengerInformationType", propOrder = {
    "numberOfPassengers",
    "passengerCategoryCode",
    "passengerTariffGroup",
    "person"
})
public class PassengerInformationType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfPassengers;
    protected PassengerCategoryCodeType passengerCategoryCode;
    protected Description80Type passengerTariffGroup;
    protected List<PersonType> person;

    /**
     * Gets the value of the numberOfPassengers property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfPassengers() {
        return numberOfPassengers;
    }

    /**
     * Sets the value of the numberOfPassengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfPassengers(BigInteger value) {
        this.numberOfPassengers = value;
    }

    /**
     * Gets the value of the passengerCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link PassengerCategoryCodeType }
     *     
     */
    public PassengerCategoryCodeType getPassengerCategoryCode() {
        return passengerCategoryCode;
    }

    /**
     * Sets the value of the passengerCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassengerCategoryCodeType }
     *     
     */
    public void setPassengerCategoryCode(PassengerCategoryCodeType value) {
        this.passengerCategoryCode = value;
    }

    /**
     * Gets the value of the passengerTariffGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Description80Type }
     *     
     */
    public Description80Type getPassengerTariffGroup() {
        return passengerTariffGroup;
    }

    /**
     * Sets the value of the passengerTariffGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description80Type }
     *     
     */
    public void setPassengerTariffGroup(Description80Type value) {
        this.passengerTariffGroup = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the person property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonType }
     * 
     * 
     */
    public List<PersonType> getPerson() {
        if (person == null) {
            person = new ArrayList<PersonType>();
        }
        return this.person;
    }

}
