//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.28 at 12:23:59 PM CST 
//


package com.gs1.artworkcontent;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TransportTrackingLogEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportTrackingLogEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="logEventDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="transportTrackingObservation" type="{urn:gs1:ecom:ecom_common:xsd:3}TransportTrackingObservationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="transportTrackingSensorObservation" type="{urn:gs1:ecom:ecom_common:xsd:3}TransportTrackingSensorObservationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportTrackingLogEventType", propOrder = {
    "logEventDateTime",
    "transportTrackingObservation",
    "transportTrackingSensorObservation"
})
public class TransportTrackingLogEventType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar logEventDateTime;
    protected List<TransportTrackingObservationType> transportTrackingObservation;
    protected List<TransportTrackingSensorObservationType> transportTrackingSensorObservation;

    /**
     * Gets the value of the logEventDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLogEventDateTime() {
        return logEventDateTime;
    }

    /**
     * Sets the value of the logEventDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLogEventDateTime(XMLGregorianCalendar value) {
        this.logEventDateTime = value;
    }

    /**
     * Gets the value of the transportTrackingObservation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportTrackingObservation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportTrackingObservation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransportTrackingObservationType }
     * 
     * 
     */
    public List<TransportTrackingObservationType> getTransportTrackingObservation() {
        if (transportTrackingObservation == null) {
            transportTrackingObservation = new ArrayList<TransportTrackingObservationType>();
        }
        return this.transportTrackingObservation;
    }

    /**
     * Gets the value of the transportTrackingSensorObservation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportTrackingSensorObservation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportTrackingSensorObservation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransportTrackingSensorObservationType }
     * 
     * 
     */
    public List<TransportTrackingSensorObservationType> getTransportTrackingSensorObservation() {
        if (transportTrackingSensorObservation == null) {
            transportTrackingSensorObservation = new ArrayList<TransportTrackingSensorObservationType>();
        }
        return this.transportTrackingSensorObservation;
    }

}
